<a href="https://colab.research.google.com/github/AhmedMorra1/DataSciencePractice/blob/master/League_of_Legends_Worlds_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# League of Legends World Championship 2019

This notebook is made to practice my data scince skills on a data set from a field that I enjoy so much, esports in general but specificaly my favorite tournment from my favorite game League of Legends World Championship. 

Now let's get our data set for all matches in the tournment.

In [0]:
!wget http://oracleselixir.com/gamedata/2019-worlds/

--2019-11-16 12:30:03--  http://oracleselixir.com/gamedata/2019-worlds/
Resolving oracleselixir.com (oracleselixir.com)... 69.73.182.198
Connecting to oracleselixir.com (oracleselixir.com)|69.73.182.198|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 826550 (807K) [application/vnd.openxmlformats-officedocument.spreadsheetml.sheet]
Saving to: ‘index.html’

index.html          100%[===================>] 807.18K  5.25MB/s    in 0.2s    

2019-11-16 12:30:05 (5.25 MB/s) - ‘index.html’ saved [826550/826550]



Import the needed libraries

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
pd.set_option('display.max_column',None)
pd.set_option('display.max_row',None)

Put the data set into a dataframe 

In [0]:
df = pd.read_excel('index.html')
df.head()

gameid                                                url league   split  \
0  1070340  https://matchhistory.euw.leagueoflegends.com/e...     WC  2019-W   
1  1070340  https://matchhistory.euw.leagueoflegends.com/e...     WC  2019-W   
2  1070340  https://matchhistory.euw.leagueoflegends.com/e...     WC  2019-W   
3  1070340  https://matchhistory.euw.leagueoflegends.com/e...     WC  2019-W   
4  1070340  https://matchhistory.euw.leagueoflegends.com/e...     WC  2019-W   

           date   week game  patchno  playerid  side position   player  \
0  43740.286146  PI-RR    1     9.19         1  Blue      Top      Evi   
1  43740.286146  PI-RR    1     9.19         2  Blue   Jungle    Steal   
2  43740.286146  PI-RR    1     9.19         3  Blue   Middle    Ceros   
3  43740.286146  PI-RR    1     9.19         4  Blue      ADC  Yutapon   
4  43740.286146  PI-RR    1     9.19         5  Blue  Support    Gaeng   

                 team  champion    ban1       ban2   ban3   ban4  ban5  \
0  DetonatioN FocusMe      Gnar  Qiyana  Gangplank  Akali  Elise  Olaf   
1  DetonatioN FocusMe      Ekko  Qiyana  Gangplank  Akali  Elise  Olaf   
2  DetonatioN FocusMe  Nocturne  Qiyana  Gangplank  Akali  Elise  Olaf   
3  DetonatioN FocusMe    Lucian  Qiyana  Gangplank  Akali  Elise  Olaf   
4  DetonatioN FocusMe    Thresh  Qiyana  Gangplank  Akali  Elise  Olaf   

   gamelength  result  k  d  a  teamkills  teamdeaths doubles triples quadras  \
0   26.533333       0  0  4  4          7          22       0       0       0   
1   26.533333       0  1  4  5          7          22       0       0       0   
2   26.533333       0  1  5  6          7          22       0       0       0   
3   26.533333       0  3  4  1          7          22       1       0       0   
4   26.533333       0  2  5  2          7          22       0       0       0   

  pentas  fb  fbassist  fbvictim    fbtime       kpm      okpm      ckpm  fd  \
0      0   0         0         0  3.879983  0.000000  0.037688  1.092965   0   
1      0   0         0         0  3.879983  0.037688  0.263819  1.092965   1   
2      0   0         0         0  3.879983  0.037688  0.113065  1.092965   0   
3      0   0         0         0  3.879983  0.113065  0.414573  1.092965   0   
4      0   0         0         1  3.879983  0.075377  0.000000  1.092965   0   

     fdtime  teamdragkills  oppdragkills  elementals  oppelementals  \
0  9.717567              1             2           0              0   
1  9.717567              1             2           1              2   
2  9.717567              1             2           0              0   
3  9.717567              1             2           0              0   
4  9.717567              1             2           0              0   

   firedrakes  waterdrakes  earthdrakes  airdrakes  elders  oppelders  herald  \
0           0            0            0          0       0          0       0   
1           0            0            0          1       0          0       0   
2           0            0            0          0       0          0       0   
3           0            0            0          0       0          0       0   
4           0            0            0          0       0          0       0   

   heraldtime  ft     fttime  firstmidouter  firsttothreetowers  \
0         NaN   0  13.588567              0                   0   
1         NaN   0  13.588567              0                   0   
2         NaN   0  13.588567              0                   0   
3         NaN   0  13.588567              0                   0   
4         NaN   0  13.588567              0                   0   

   teamtowerkills  opptowerkills  fbaron  fbarontime  teambaronkills  \
0               1             10     0.0   23.779817               0   
1               1             10     0.0   23.779817               0   
2               1             10     0.0   23.779817               0   
3               1             10     0.0   23.779817        

Let's see how many attributes we can make analysis on

In [0]:
print('We have',df.shape[1],'attributes to work on.')

We have 98 attributes to work on.


As you can see teams and players both are in the same dataframe so I will seperate them to make our mission easier

Let's start with teams

In [0]:
teamdf = df.loc[df['position']=='Team',:]
teamdf.head()

gameid                                                url league   split  \
10  1070340  https://matchhistory.euw.leagueoflegends.com/e...     WC  2019-W   
11  1070340  https://matchhistory.euw.leagueoflegends.com/e...     WC  2019-W   
22  1070330  https://matchhistory.euw.leagueoflegends.com/e...     WC  2019-W   
23  1070330  https://matchhistory.euw.leagueoflegends.com/e...     WC  2019-W   
34  1070349  https://matchhistory.euw.leagueoflegends.com/e...     WC  2019-W   

            date   week game  patchno  playerid  side position player  \
10  43740.286146  PI-RR    1     9.19       100  Blue     Team   Team   
11  43740.286146  PI-RR    1     9.19       200   Red     Team   Team   
22  43740.223889  PI-RR    1     9.19       100  Blue     Team   Team   
23  43740.223889  PI-RR    1     9.19       200   Red     Team   Team   
34  43740.329711  PI-RR    1     9.19       100  Blue     Team   Team   

                  team champion          ban1       ban2       ban3  \
10  DetonatioN FocusMe                 Qiyana  Gangplank      Akali   
11              Splyce           Heimerdinger   Pantheon     Syndra   
22       Clutch Gaming                 Syndra      Yuumi     Qiyana   
23    Unicorns of Love               Pantheon     Rumble  Gangplank   
34             Mammoth                 Qiyana      Kayle    Morgana   

          ban4    ban5  gamelength  result   k   d   a  teamkills  teamdeaths  \
10       Elise    Olaf   26.533333       0   7  22  18          7          22   
11  Cassiopeia  Kai'Sa   26.533333       1  22   7  51         22           7   
22     Caitlyn  Draven   38.066667       0   8  16  17          8          16   
23     Skarner   Elise   38.066667       1  16   8  34         16           8   
34      Thresh    Pyke   37.583333       1  18   8  51         18           8   

   doubles triples quadras pentas  fb  fbassist  fbvictim    fbtime       kpm  \
10                                  0         0         1  3.879983  0.263819   
11                                  1         1         0  3.879983  0.829146   
22                                  1         1         0  7.924383  0.210158   
23                                  0         0         1  7.924383  0.420315   
34                                  0         0         1  3.360983  0.478936   

        okpm      ckpm  fd     fdtime  teamdragkills  oppdragkills  \
10  0.829146  1.092965   1   9.717567              1             2   
11  0.263819  1.092965   0   9.717567              2             1   
22  0.420315  0.630473   0  17.121617              0             4   
23  0.210158  0.630473   1  17.121617              4             0   
34  0.212860  0.691796   1   8.318133              4             0   

    elementals  oppelementals  firedrakes  waterdrakes  earthdrakes  \
10           1              2           0            0            0   
11           2              1           0            1            0   
22           0              4           0            0            0   
23           4              0           1            0            1   
34           4              0           1            2            1   

    airdrakes  elders  oppelders  herald  heraldtime  ft     fttime  \
10          1       0          0       0   13.109583   0  13.588567   
11          1       0          0       1   13.109583   1  13.588567   
22          0       0          0       1   13.114183   0  13.696417   
23          2       0          0       0   13.114183   1  13.696417   
34          0       0          0       1   15.583383   1  17.613883   

    firstmidouter  firsttothreetowers  teamtowerkills  opptowerkills  fbaron  \
10              0                   0               1             10     0.0   
11              1                   1              10              1     1.0   
22              0                   0               3             11     0.0   
23              1                   1              11              3     1.0   
34 

Now for players

In [0]:
playersdf = df.loc[df['position']!='Team',:]
playersdf.head()

gameid                                                url league   split  \
0  1070340  https://matchhistory.euw.leagueoflegends.com/e...     WC  2019-W   
1  1070340  https://matchhistory.euw.leagueoflegends.com/e...     WC  2019-W   
2  1070340  https://matchhistory.euw.leagueoflegends.com/e...     WC  2019-W   
3  1070340  https://matchhistory.euw.leagueoflegends.com/e...     WC  2019-W   
4  1070340  https://matchhistory.euw.leagueoflegends.com/e...     WC  2019-W   

           date   week game  patchno  playerid  side position   player  \
0  43740.286146  PI-RR    1     9.19         1  Blue      Top      Evi   
1  43740.286146  PI-RR    1     9.19         2  Blue   Jungle    Steal   
2  43740.286146  PI-RR    1     9.19         3  Blue   Middle    Ceros   
3  43740.286146  PI-RR    1     9.19         4  Blue      ADC  Yutapon   
4  43740.286146  PI-RR    1     9.19         5  Blue  Support    Gaeng   

                 team  champion    ban1       ban2   ban3   ban4  ban5  \
0  DetonatioN FocusMe      Gnar  Qiyana  Gangplank  Akali  Elise  Olaf   
1  DetonatioN FocusMe      Ekko  Qiyana  Gangplank  Akali  Elise  Olaf   
2  DetonatioN FocusMe  Nocturne  Qiyana  Gangplank  Akali  Elise  Olaf   
3  DetonatioN FocusMe    Lucian  Qiyana  Gangplank  Akali  Elise  Olaf   
4  DetonatioN FocusMe    Thresh  Qiyana  Gangplank  Akali  Elise  Olaf   

   gamelength  result  k  d  a  teamkills  teamdeaths doubles triples quadras  \
0   26.533333       0  0  4  4          7          22       0       0       0   
1   26.533333       0  1  4  5          7          22       0       0       0   
2   26.533333       0  1  5  6          7          22       0       0       0   
3   26.533333       0  3  4  1          7          22       1       0       0   
4   26.533333       0  2  5  2          7          22       0       0       0   

  pentas  fb  fbassist  fbvictim    fbtime       kpm      okpm      ckpm  fd  \
0      0   0         0         0  3.879983  0.000000  0.037688  1.092965   0   
1      0   0         0         0  3.879983  0.037688  0.263819  1.092965   1   
2      0   0         0         0  3.879983  0.037688  0.113065  1.092965   0   
3      0   0         0         0  3.879983  0.113065  0.414573  1.092965   0   
4      0   0         0         1  3.879983  0.075377  0.000000  1.092965   0   

     fdtime  teamdragkills  oppdragkills  elementals  oppelementals  \
0  9.717567              1             2           0              0   
1  9.717567              1             2           1              2   
2  9.717567              1             2           0              0   
3  9.717567              1             2           0              0   
4  9.717567              1             2           0              0   

   firedrakes  waterdrakes  earthdrakes  airdrakes  elders  oppelders  herald  \
0           0            0            0          0       0          0       0   
1           0            0            0          1       0          0       0   
2           0            0            0          0       0          0       0   
3           0            0            0          0       0          0       0   
4           0            0            0          0       0          0       0   

   heraldtime  ft     fttime  firstmidouter  firsttothreetowers  \
0         NaN   0  13.588567              0                   0   
1         NaN   0  13.588567              0                   0   
2         NaN   0  13.588567              0                   0   
3         NaN   0  13.588567              0                   0   
4         NaN   0  13.588567              0                   0   

   teamtowerkills  opptowerkills  fbaron  fbarontime  teambaronkills  \
0               1             10     0.0   23.779817               0   
1               1             10     0.0   23.779817               0   
2               1             10     0.0   23.779817               0   
3               1             10     0.0   23.779817        

Now let's see how many games were played

In [0]:
print(int((teamdf.shape[0]/2)),'matches played')

119 matches played


Now as the matched I will start with bans lets see the top 5 banned champions

Bans are seperated as 5 bans so I have to melt them into one ban column.

In [0]:
bans = teamdf[['ban1','ban2','ban3','ban4','ban5']].melt()
bans.head()

variable         value
0     ban1        Qiyana
1     ban1  Heimerdinger
2     ban1        Syndra
3     ban1      Pantheon
4     ban1        Qiyana

Now let's see what is the most banned champions

In [0]:
top5bans = bans['value'].value_counts().nlargest(5)
for i in range (0,top5bans.shape[0]):
    print(top5bans.index[i],'was banned',top5bans[i],'times, which is',str("%.2f" %((top5bans[i]/119)*100))+'% of the matches.')

Pantheon was banned 118 times, which is 99.16% of the matches.
Qiyana was banned 86 times, which is 72.27% of the matches.
Syndra was banned 66 times, which is 55.46% of the matches.
Renekton was banned 61 times, which is 51.26% of the matches.
Akali was banned 54 times, which is 45.38% of the matches.


Pantheon was the most banned champion in the tournment, 118 out of 119 matches.
Qiyana came in second with 86 bans.

Now let's see the most picked champions

In [0]:
top5picks = playersdf['champion'].value_counts().nlargest(5)
for i in range (0,top5picks.shape[0]):
    print(top5picks.index[i],'was picked',top5picks[i],'times, which is',str("%.2f" %((top5picks[i]/119)*100))+'% of the matches.')

Kai'Sa was picked 71 times, which is 59.66% of the matches.
Lee Sin was picked 57 times, which is 47.90% of the matches.
Xayah was picked 56 times, which is 47.06% of the matches.
Nautilus was picked 52 times, which is 43.70% of the matches.
Gragas was picked 49 times, which is 41.18% of the matches.


Kai'Sa was the most picked champion in the tournment, 71 out of 119 matches. Lee Sin came in second with 57 picks.

Now let's split the players data frame to explore each rule seperately 

In [0]:
top = playersdf.loc[playersdf['position']=='Top']
mid = playersdf.loc[playersdf['position']=='Middle']
bot = playersdf.loc[playersdf['position']=='ADC']
support = playersdf.loc[playersdf['position']=='Support']
jungle = playersdf.loc[playersdf['position']=='Jungle']

Now let's explore the top picked champions in every rule

In [0]:
print('Top 5 picked champions in Top:')
print(top['champion'].value_counts().nlargest(5))

Top 5 picked champions in Top:
Gangplank    38
Renekton     28
Gnar         18
Jayce        15
Vladimir     14
Name: champion, dtype: int64


In [0]:
print('Top 5 picked champions in Mid:')
print(mid['champion'].value_counts().nlargest(5))

Top 5 picked champions in Mid:
Ryze       29
Akali      24
Syndra     21
LeBlanc    21
Orianna    12
Name: champion, dtype: int64


In [0]:
print('Top 5 picked champions in Bot:')
print(bot['champion'].value_counts().nlargest(5))

Top 5 picked champions in Bot:
Kai'Sa    71
Xayah     56
Ezreal    22
Lucian    10
Varus      9
Name: champion, dtype: int64


In [0]:
print('Top 5 picked champions in Support:')
print(support['champion'].value_counts().nlargest(5))

Top 5 picked champions in Support:
Nautilus    48
Rakan       42
Thresh      35
Leona       20
Alistar     14
Name: champion, dtype: int64


In [0]:
print('Top 5 picked champions in Jungle:')
print(jungle['champion'].value_counts().nlargest(5))

Top 5 picked champions in Jungle:
Lee Sin      57
Gragas       40
Elise        32
Rek'Sai      22
Jarvan IV    18
Name: champion, dtype: int64


We will do some complicated analysis with these dataframes later

Now let's explore the periods of the matches

In [0]:
timedf = teamdf.loc[teamdf['side']=='Red'] #picking only one side of the match to get the times only once
timedf.head(3)

gameid                                                url league   split  \
11  1070340  https://matchhistory.euw.leagueoflegends.com/e...     WC  2019-W   
23  1070330  https://matchhistory.euw.leagueoflegends.com/e...     WC  2019-W   
35  1070349  https://matchhistory.euw.leagueoflegends.com/e...     WC  2019-W   

            date   week game  patchno  playerid side position player  \
11  43740.286146  PI-RR    1     9.19       200  Red     Team   Team   
23  43740.223889  PI-RR    1     9.19       200  Red     Team   Team   
35  43740.329711  PI-RR    1     9.19       200  Red     Team   Team   

                team champion          ban1      ban2       ban3        ban4  \
11            Splyce           Heimerdinger  Pantheon     Syndra  Cassiopeia   
23  Unicorns of Love               Pantheon    Rumble  Gangplank     Skarner   
35  Unicorns of Love               Pantheon  Vladimir      Rakan       Xayah   

      ban5  gamelength  result   k   d   a  teamkills  teamdeaths doubles  \
11  Kai'Sa   26.533333       1  22   7  51         22           7           
23   Elise   38.066667       1  16   8  34         16           8           
35  Lucian   37.583333       0   8  18  12          8          18           

   triples quadras pentas  fb  fbassist  fbvictim    fbtime       kpm  \
11                          1         1         0  3.879983  0.829146   
23                          0         0         1  7.924383  0.420315   
35                          1         1         0  3.360983  0.212860   

        okpm      ckpm  fd     fdtime  teamdragkills  oppdragkills  \
11  0.263819  1.092965   0   9.717567              2             1   
23  0.210158  0.630473   1  17.121617              4             0   
35  0.478936  0.691796   0   8.318133              0             4   

    elementals  oppelementals  firedrakes  waterdrakes  earthdrakes  \
11           2              1           0            1            0   
23           4              0           1            0            1   
35           0              4           0            0            0   

    airdrakes  elders  oppelders  herald  heraldtime  ft     fttime  \
11          1       0          0       1   13.109583   1  13.588567   
23          2       0          0       0   13.114183   1  13.696417   
35          0       0          0       0   15.583383   0  17.613883   

    firstmidouter  firsttothreetowers  teamtowerkills  opptowerkills  fbaron  \
11              1                   1              10              1     1.0   
23              1                   1              11              3     1.0   
35              0                   0               2              9     0.0   

    fbarontime  teambaronkills  oppbaronkills  dmgtochamps  \
11   23.779817               1              0        59544   
23   22.977400               2              0        73706   
35   27.446517               0              1        52317   

    dmgtochampsperminute dmgshare earnedgoldshare  wards       wpm  wardshare  \
11           2244.120603                              80  3.015075        1.0   
23           1936.234676                             135  3.546410        1.0   
35           1392.026608                             134  3.565410        1.0   

    wardkills      wcpm  visionwards  visionwardbuys visiblewardclearrate  \
11         51  1.922111           35              41             0.710526   
23         62  1.628722           35              35             0.580645   
35         57  1.516630           32              36             0.655172   

   invisiblewardclearrate  totalgold    earnedgpm  goldspent      gspd  \
11               0.280702      56670  1471.869347      49760  0.243463   
23               0.212766      68625  1154.558669      64045  0.085392   
35               0.333333      60326   956.461197      58358 -0.035762   

    minionkills  monsterkills  monsterkillsownjungle  monsterkillsenemyjungle  \
11          688           188      

Now let's get the stats on match times

In [0]:
timedf['gamelength'].describe()

count    119.000000
mean      33.292857
std        6.460870
min       22.716667
25%       28.483333
50%       32.083333
75%       37.283333
max       63.416667
Name: gamelength, dtype: float64

Maximum Match Time is 63.41 Minutes

Average Match Time is 33.29 Minutes

Minimum Match Time is 22.71 Minutes

Let's find which matches had the max and min length 

In [0]:
maxtime = teamdf.loc[teamdf['gamelength']==teamdf['gamelength'].max()]
mintime = teamdf.loc[teamdf['gamelength']==teamdf['gamelength'].min()]
print("Maximum Match Time is game number {} between {} and {}".format(maxtime['game'].tolist()[0],maxtime['team'].tolist()[0],maxtime['team'].tolist()[1]))
print("Minimum Match Time is game number {} between {} and {}".format(mintime['game'].tolist()[0],mintime['team'].tolist()[0],mintime['team'].tolist()[1]))

Maximum Match Time is game number 3 between Isurus Gaming and DetonatioN FocusMe
Minimum Match Time is game number 4 between Lowkey Esports and Damwon Gaming


Now let's explore which side Blue or Red has the most wins

In [0]:
side = teamdf[['side','result']]
side.groupby('side')['result'].value_counts()

side  result
Blue  1         62
      0         57
Red   0         62
      1         57
Name: result, dtype: int64

Blue side won 62 matches which is 52% of the matches

Now let's see which team has most kills and deaths in a game

In [0]:
maxkills = teamdf.loc[teamdf['teamkills']==teamdf['teamkills'].max()]
minkills = teamdf.loc[teamdf['teamkills']==teamdf['teamkills'].min()]
print('Max kills for a team in a single game is {} for {} against {}'.format(maxkills['teamkills'].tolist()[0],maxkills['team'].tolist()[0],teamdf.loc[teamdf['gameid']==maxkills['gameid'].tolist()[0]]['team'].tolist()[0]))
print('Min kills for a team in a single game is {} for {} against {}'.format(minkills['teamkills'].tolist()[0],minkills['team'].tolist()[0],teamdf.loc[teamdf['gameid']==minkills['gameid'].tolist()[0]]['team'].tolist()[1]))

Max kills for a team in a single game is 34 for Funplus Phoenix against Invictus Gaming
Min kills for a team in a single game is 1 for Mammoth against Unicorns of Love


In [0]:
maxdeaths = teamdf.loc[teamdf['teamdeaths']==teamdf['teamdeaths'].max()]
mindeaths = teamdf.loc[teamdf['teamdeaths']==teamdf['teamdeaths'].min()]
print('Max deaths for a team in a single game is {} for {} against {}'.format(maxdeaths['teamdeaths'].tolist()[0],maxdeaths['team'].tolist()[0],teamdf.loc[teamdf['gameid']==maxdeaths['gameid'].tolist()[0]]['team'].tolist()[1]))
print('Min deaths for a team in a single game is {} for {} against {}'.format(mindeaths['teamdeaths'].tolist()[0],mindeaths['team'].tolist()[0],teamdf.loc[teamdf['gameid']==mindeaths['gameid'].tolist()[0]]['team'].tolist()[1]))

Max deaths for a team in a single game is 34 for Invictus Gaming against Funplus Phoenix
Min deaths for a team in a single game is 1 for Griffin against Cloud9


Now Let's see How many double/triple/quadra/penta kills happend 

In [0]:
print("There was {} Double Kills".format(playersdf['doubles'].sum()))
print("There was {} Triple Kills".format(playersdf['triples'].sum()))
print("There was {} Quadra Kills".format(playersdf['quadras'].sum()))
print("There was {} Penta Kills".format(playersdf['pentas'].sum()))

There was 313 Double Kills
There was 59 Triple Kills
There was 7 Quadra Kills
There was 1 Penta Kills


In [0]:
player = playersdf[['player','doubles','triples','quadras','pentas','k','d','a','fb','fbvictim','fbassist','fbtime']]
playerdoubles = player.groupby('player')['doubles'].sum()
playertriples = player.groupby('player')['triples'].sum()
playerquadras = player.groupby('player')['quadras'].sum()
playerpentas = player.groupby('player')['pentas'].sum()
print("Max Double kills is {} by {}".format(playerdoubles.max(),playerdoubles.loc[playerdoubles == playerdoubles.max()].index[0]))
print("Max Triple kills is {} by {}".format(playertriples.max(),playertriples.loc[playertriples == playertriples.max()].index[0]))
print("Max Quadra kills is {} by {}".format(playerquadras.max(),playerquadras.loc[playerquadras == playerquadras.max()].index[0]))
print("Max Penta kills is {} by {}".format(playerpentas.max(),playerpentas.loc[playerpentas == playerpentas.max()].index[0]))

Max Double kills is 21 by Lwx
Max Triple kills is 6 by JackeyLove
Max Quadra kills is 2 by Cody Sun
Max Penta kills is 1 by Viper


Now let's see Max/Min Kills/Deaths for all then for each rule

In [0]:
playerkills = player.groupby('player')['k'].sum()
playerdeaths = player.groupby('player')['d'].sum()
playerassists = player.groupby('player')['a'].sum()
print("Max kills is {} by {}".format(playerkills.max(),playerkills.loc[playerkills == playerkills.max()].index[0]))
print("Max deaths is {} by {}".format(playerdeaths.max(),playerdeaths.loc[playerdeaths == playerdeaths.max()].index[0]))
print("Max assists is {} by {}".format(playerassists.max(),playerassists.loc[playerassists == playerassists.max()].index[0]))
print("Min kills is {} by {}".format(playerkills.min(),playerkills.loc[playerkills == playerkills.min()].index[0]))
print("Min deaths is {} by {}".format(playerdeaths.min(),playerdeaths.loc[playerdeaths == playerdeaths.min()].index[0]))
print("Min assists is {} by {}".format(playerassists.min(),playerassists.loc[playerassists == playerassists.min()].index[0]))

Max kills is 110 by Lwx
Max deaths is 70 by Humanoid
Max assists is 213 by Crisp
Min kills is 1 by Apex
Min deaths is 0 by Deftly
Min assists is 0 by Hieu3


Now let's explore the First Blood 

In [0]:
firstbloodkill = player.groupby('player')['fb'].sum()
firstbloodassist = player.groupby('player')['fbassist'].sum()
firstblooddeath = player.groupby('player')['fbvictim'].sum()
print("Max First Blood Kills is {} by {}".format(firstbloodkill.max(),firstbloodkill.loc[firstbloodkill == firstbloodkill.max()].index[0]))
print("Max First Blood Assist is {} by {}".format(firstbloodassist.max(),firstbloodassist.loc[firstbloodassist == firstbloodassist.max()].index[0]))
print("Max Fist Blood Victim is {} by {}".format(firstblooddeath.max(),firstblooddeath.loc[firstblooddeath == firstblooddeath.max()].index[0]))

Max First Blood Kills is 5 by GimGoon
Max First Blood Assist is 7 by Doinb
Max Fist Blood Victim is 6 by Vizicsacsi


Now Let's find Max/Min First Blood time

In [0]:
LowestFBt = player['fbtime'].min()
HighestFBt = player['fbtime'].max()
lowteam = teamdf.loc[teamdf['fbtime']==player['fbtime'].min()]['team'].tolist()
highteam = teamdf.loc[teamdf['fbtime']==player['fbtime'].max()]['team'].tolist()
lowkiller = playersdf.loc[(playersdf['fbtime']==player['fbtime'].min()) & (playersdf['fb']==1) ]['player'].tolist()[0]
lowvictim = playersdf.loc[(playersdf['fbtime']==player['fbtime'].min()) & (playersdf['fbvictim']==1)]['player'].tolist()[0]
highkiller = playersdf.loc[(playersdf['fbtime']==player['fbtime'].max()) & (playersdf['fb']==1) ]['player'].tolist()[0]
highvictim = playersdf.loc[(playersdf['fbtime']==player['fbtime'].max()) & (playersdf['fbvictim']==1)]['player'].tolist()[0]
print('Fastest First Blood happend after',"%.2f" %LowestFBt,'minutes in the match between {} and {}, {} was killed by {}'.format(lowteam[0],lowteam[1],lowvictim,lowkiller))
print('Slowest First Blood happend after',"%.2f" %HighestFBt,'minutes in the match between {} and {}, {} was killed by {}'.format(highteam[0],highteam[1],highvictim,highkiller))

Fastest First Blood happend after 0.70 minutes in the match between Clutch Gaming and Fnatic, Vulcan was killed by Bwipo
Slowest First Blood happend after 15.36 minutes in the match between Clutch Gaming and Mammoth, Fudge was killed by Lira


Now Let's Explore Kills per minute for teams and players for individual games then the average of all games

Let's start with individual games for teams

In [0]:
kpmteamh = teamdf.loc[teamdf['kpm']==teamdf['kpm'].max()]['team'].tolist()[0]
kpmh = "%.2f" %teamdf.loc[teamdf['kpm']==teamdf['kpm'].max()]['kpm'].tolist()[0]
kpmteaml = teamdf.loc[teamdf['kpm']==teamdf['kpm'].min()]['team'].tolist()[0]
kpml = "%.2f" %teamdf.loc[teamdf['kpm']==teamdf['kpm'].min()]['kpm'].tolist()[0]
gameh = teamdf.loc[teamdf['kpm']==teamdf['kpm'].max()]['gameid'].tolist()[0]
gamel = teamdf.loc[teamdf['kpm']==teamdf['kpm'].min()]['gameid'].tolist()[0]
opkpmteamh = teamdf.loc[teamdf['gameid']==gameh]['team'].tolist()[1]
opkpmteaml = teamdf.loc[teamdf['gameid']==gamel]['team'].tolist()[1]
print('Highest Kill Per Minute Team is {} with {} KPM against {}.'.format(kpmteamh,kpmh,opkpmteamh))
print('Lowest Kill Per Minute Team is {} with {} KPM against {}.'.format(kpmteaml,kpml,opkpmteaml))
print('Average Kill Per Minute for teams in all matches is {} KPM.'.format("%.2f" %teamdf['kpm'].mean()))

Highest Kill Per Minute Team is G2 Esports with 1.06 KPM against Cloud9.
Lowest Kill Per Minute Team is Mammoth with 0.04 KPM against Unicorns of Love.
Average Kill Per Minute for teams in all matches is 0.40 KPM.


Now with individual games for players

In [0]:
kpmplayerh = playersdf.loc[playersdf['kpm']==playersdf['kpm'].max()]['player'].tolist()[0]
pkpmh = "%.2f" %playersdf.loc[playersdf['kpm']==playersdf['kpm'].max()]['kpm'].tolist()[0]
kpmplayerl = playersdf.loc[playersdf['kpm']==playersdf['kpm'].min()]['player'].tolist()[0]
pkpml = "%.2f" %playersdf.loc[playersdf['kpm']==playersdf['kpm'].min()]['kpm'].tolist()[0]
pgameh = playersdf.loc[playersdf['kpm']==playersdf['kpm'].max()]['gameid'].tolist()[0]
pgamel = playersdf.loc[playersdf['kpm']==playersdf['kpm'].min()]['gameid'].tolist()[0]
opkpmteamh = teamdf.loc[teamdf['gameid']==pgameh]['team'].tolist()[0]
opkpmteaml = teamdf.loc[teamdf['gameid']==pgamel]['team'].tolist()[1]
print("Highest Kill Per Minute Player is {} with {} KPM against {}.".format(kpmplayerh,pkpmh,opkpmteamh))
print("Lowest Kill Per Minute Player is {} with {} KPM against {}.".format(kpmplayerl,pkpml,opkpmteaml))
print('Average Kill Per Minute for players in all matches is {} KPM.'.format("%.2f" %playersdf['kpm'].mean()))

Highest Kill Per Minute Player is Lwx with 0.45 KPM against Fnatic.
Lowest Kill Per Minute Player is Evi with 0.00 KPM against Splyce.
Average Kill Per Minute for players in all matches is 0.08 KPM.


Now let's get the averages

In [0]:
avgkpmt = teamdf.groupby('team')['kpm'].mean()
avgkpmp = playersdf.groupby('player')['kpm'].mean()
print('The Highest Average KPM Team is {} with {} KPM.'.format(avgkpmt.loc[avgkpmt == avgkpmt.max()].index.tolist()[0],"%.2f" %avgkpmt.max()))
print('The Lowest Average KPM Team is {} with {} KPM.'.format(avgkpmt.loc[avgkpmt == avgkpmt.min()].index.tolist()[0],"%.2f" %avgkpmt.min()))
print('The Highest Average KPM Player is {} with {} KPM.'.format(avgkpmp.loc[avgkpmp == avgkpmp.max()].index.tolist()[0],"%.2f" %avgkpmp.max()))
print('The Lowest Average KPM Player is {} with {} KPM.'.format(avgkpmp.loc[avgkpmp == avgkpmp.min()].index.tolist()[0],"%.2f" %avgkpmp.min()))

The Highest Average KPM Team is Funplus Phoenix with 0.61 KPM.
The Lowest Average KPM Team is AHQ e-Sports Club with 0.22 KPM.
The Highest Average KPM Player is Lwx with 0.20 KPM.
The Lowest Average KPM Player is Ysera with 0.00 KPM.


In [0]:
#Let me check that
playersdf.loc[playersdf['player']=='Lwx']['kpm'].mean()

0.19823830875294468

Now Let's Explore the KDA of the players

In [0]:
rules = ['Top','Jungle','Middle','ADC','Support']
for i in rules:
    kda = playersdf.loc[playersdf['position']==i].groupby(['player'])['k','d','a'].sum()
    kda['kda'] = (kda['k']+kda['a'])/kda['d'] 
    print('{} has the highest KDA as {} with {} KDA.'.format(kda.loc[kda['kda']==kda['kda'].max()].index.tolist()[0],i,"%.2f" %kda['kda'].max()))

ShowMaker has the highest KDA as Top with 10.00 KDA.
Broxah has the highest KDA as Jungle with 5.41 KDA.
ShowMaker has the highest KDA as Middle with 7.50 KDA.
Deftly has the highest KDA as ADC with inf KDA.
Lehends has the highest KDA as Support with 8.44 KDA.


In [0]:
kda2 = playersdf.loc[playersdf['position']=='Top'].groupby(['player'])['k','d','a'].sum()
kda2['kda'] = (kda2['k']+kda2['a'])/kda2['d'] 
kda2.sort_values(by=['kda'],ascending=False).head()

k   d    a        kda
player                           
ShowMaker   5   1    5  10.000000
GimGoon    51  39  117   4.307692
Khan       60  34   67   3.735294
Langx      15  13   26   3.153846
Nuguri     45  45   96   3.133333

ShowMaker is TOP ??? hmmm

In [0]:
playersdf.loc[playersdf['position']=='Top']['player'].unique()

array(['Evi', 'Vizicsacsi', 'Huni', 'BOSS', 'Fudge', 'Buggax', 'Armut',
       'Nuguri', 'Rockky', '3z', 'ShowMaker', 'Robo', 'Hani', 'Cyeol',
       'Bwipo', 'Khan', 'Langx', 'TheShy', 'Ziv', 'Impact', 'Rest',
       'GimGoon', 'Zeros', 'Sword', 'Wunder', 'Licorice'], dtype=object)

He is registered as top, Let's check which game

In [0]:
playersdf.loc[(playersdf['position']=='Top') & (playersdf['player']=='ShowMaker')]

gameid                                                url league   split  \
96  1070445  https://matchhistory.euw.leagueoflegends.com/e...     WC  2019-W   

           date   week game  patchno  playerid  side position     player  \
96  43741.32772  PI-RR    2     9.19         1  Blue      Top  ShowMaker   

             team  champion   ban1    ban2    ban3   ban4    ban5  gamelength  \
96  Damwon Gaming  Renekton  Yuumi  Draven  Syndra  Xayah  Irelia   30.133333   

    result  k  d  a  teamkills  teamdeaths doubles triples quadras pentas  fb  \
96       1  5  1  5         22          11       0       0       0      0   0   

    fbassist  fbvictim    fbtime       kpm      okpm      ckpm  fd    fdtime  \
96         1         0  3.540917  0.165929  0.033186  1.095133   0  9.971533   

    teamdragkills  oppdragkills  elementals  oppelementals  firedrakes  \
96              3             1           0              0           0   

    waterdrakes  earthdrakes  airdrakes  elders  oppelders  herald  \
96            0            0          0       0          0       1   

    heraldtime  ft     fttime  firstmidouter  firsttothreetowers  \
96         NaN   1  10.670683              1                   1   

    teamtowerkills  opptowerkills  fbaron  fbarontime  teambaronkills  \
96              11              0     1.0   26.253433               1   

    oppbaronkills  dmgtochamps  dmgtochampsperminute  dmgshare  \
96              0        20564            682.433628  0.271461   

   earnedgoldshare  wards       wpm  wardshare  wardkills      wcpm  \
96        0.236521     16  0.530973   0.144144          7  0.232301   

    visionwards  visionwardbuys visiblewardclearrate invisiblewardclearrate  \
96            6               7                                               

    totalgold   earnedgpm  goldspent      gspd  minionkills  monsterkills  \
96      14374  345.467257      13025  0.257855          248            15   

    monsterkillsownjungle  monsterkillsenemyjungle      cspm  goldat10  \
96                      3                        8  8.727876      4425   

    oppgoldat10  gdat10  goldat15  oppgoldat15  gdat15  xpat10  oppxpat10  \
96         2497    1928      6776         4522    2254    4931       3461   

    xpdat10  csat10  oppcsat10  csdat10  csat15  oppcsat15  csdat15  
96     1470      81         41       40     131         97       34

let's check all the players in this game

In [0]:
df.loc[(df['gameid']==1070445)]

gameid                                                url league  \
96   1070445  https://matchhistory.euw.leagueoflegends.com/e...     WC   
97   1070445  https://matchhistory.euw.leagueoflegends.com/e...     WC   
98   1070445  https://matchhistory.euw.leagueoflegends.com/e...     WC   
99   1070445  https://matchhistory.euw.leagueoflegends.com/e...     WC   
100  1070445  https://matchhistory.euw.leagueoflegends.com/e...     WC   
101  1070445  https://matchhistory.euw.leagueoflegends.com/e...     WC   
102  1070445  https://matchhistory.euw.leagueoflegends.com/e...     WC   
103  1070445  https://matchhistory.euw.leagueoflegends.com/e...     WC   
104  1070445  https://matchhistory.euw.leagueoflegends.com/e...     WC   
105  1070445  https://matchhistory.euw.leagueoflegends.com/e...     WC   
106  1070445  https://matchhistory.euw.leagueoflegends.com/e...     WC   
107  1070445  https://matchhistory.euw.leagueoflegends.com/e...     WC   

      split         date   week game  patchno  playerid  side position  \
96   2019-W  43741.32772  PI-RR    2     9.19         1  Blue      Top   
97   2019-W  43741.32772  PI-RR    2     9.19         2  Blue   Jungle   
98   2019-W  43741.32772  PI-RR    2     9.19         3  Blue   Middle   
99   2019-W  43741.32772  PI-RR    2     9.19         4  Blue      ADC   
100  2019-W  43741.32772  PI-RR    2     9.19         5  Blue  Support   
101  2019-W  43741.32772  PI-RR    2     9.19         6   Red      Top   
102  2019-W  43741.32772  PI-RR    2     9.19         7   Red   Jungle   
103  2019-W  43741.32772  PI-RR    2     9.19         8   Red   Middle   
104  2019-W  43741.32772  PI-RR    2     9.19         9   Red      ADC   
105  2019-W  43741.32772  PI-RR    2     9.19        10   Red  Support   
106  2019-W  43741.32772  PI-RR    2     9.19       100  Blue     Team   
107  2019-W  43741.32772  PI-RR    2     9.19       200   Red     Team   

        player           team  champion      ban1    ban2    ban3      ban4  \
96   ShowMaker  Damwon Gaming  Renekton     Yuumi  Draven  Syndra     Xayah   
97      Canyon  Damwon Gaming   Taliyah     Yuumi  Draven  Syndra     Xayah   
98      Nuguri  Damwon Gaming      Ryze     Yuumi  Draven  Syndra     Xayah   
99     Nuclear  Damwon Gaming    Kai'Sa     Yuumi  Draven  Syndra     Xayah   
100      BeryL  Damwon Gaming      Pyke     Yuumi  Draven  Syndra     Xayah   
101       Robo       Flamengo    Aatrox  Pantheon  Qiyana  Gragas  Nautilus   
102     Shrimp       Flamengo   Rek'Sai  Pantheon  Qiyana  Gragas  Nautilus   
103       Goku       Flamengo     Neeko  Pantheon  Qiyana  Gragas  Nautilus   
104       brTT       Flamengo   Caitlyn  Pantheon  Qiyana  Gragas  Nautilus   
105       Luci       Flamengo    Thresh  Pantheon  Qiyana  Gragas  Nautilus   
106       Team  Damwon Gaming               Yuumi  Draven  Syndra     Xayah   
107       Team       Flamengo            Pantheon  Qiyana  Gragas  Nautilus   

        ban5  gamelength  result   k   d   a  teamkills  teamdeaths doubles  \
96    Irelia   30.133333       1   5   1   5         22          11       0   
97    Irelia   30.133333       1   6   1  10         22          11       1   
98    Irelia   30.133333       1   3   4   8         22          11       0   
99    Irelia   30.133333       1   8   0   4         22          11       2   
100   Irelia   30.133333       1   0   5   7         22          11       0   
101  Alistar   30.133333       0   1   5   7         11          22       0   
102  Alistar   30.133333       0   6   6   1         11          22       1   
103  Alistar   30.133333       0   2   4   6         11          22       0   
104  Alistar   30.133333       0   1   4   4         11          22       0   
105  Alistar   30.133333       0   1   3   5         11          22       0   
106   Irelia   30.133333       1  22  11  34         22          11           
107  Alistar   30.133333       0  11  22  23         11          22           

    triples quadras pent

Did niguri and showmaker switch sides this game? i will check the vods on youtube

Yup he played top that match against flamingo

Now for the lowest KDA for all rules

In [0]:
rules = ['Top','Jungle','Middle','ADC','Support']
for i in rules:
    kda = playersdf.loc[playersdf['position']==i].groupby(['player'])['k','d','a'].sum()
    kda['kda'] = (kda['k']+kda['a'])/kda['d'] 
    print('{} has the lowest KDA as {} with {} KDA.'.format(kda.loc[kda['kda']==kda['kda'].min()].index.tolist()[0],i,"%.2f" %kda['kda'].min()))

Cyeol has the lowest KDA as Top with 0.50 KDA.
Blaber has the lowest KDA as Jungle with 1.71 KDA.
Armut has the lowest KDA as Middle with 0.33 KDA.
Sneaky has the lowest KDA as ADC with 1.84 KDA.
Hieu3 has the lowest KDA as Support with 1.00 KDA.


Which team is the deadliest(most kills)?

In [0]:
teamdf.groupby('team')['k'].sum().nlargest(5)

team
Funplus Phoenix    335
Splyce             298
Damwon Gaming      273
G2 Esports         242
SK Telecom T1      217
Name: k, dtype: int64

Funplus Phoenix is the deadliest team with 335 kills followed by Splyce with 298 kills

Now which team has the most deaths?

In [0]:
teamdf.groupby('team')['d'].sum().nlargest(5)

team
Splyce             265
G2 Esports         259
Invictus Gaming    227
Funplus Phoenix    199
Damwon Gaming      188
Name: d, dtype: int64

Splyce is the most killed team with 265 deaths followed by G2 Esports with 259 deaths

Let's explore Champions for a change 

Top 5 champions with the highest win rate

In [0]:
champplays = playersdf.groupby('champion')['result'].count()
champplays = champplays.reset_index()

champwins = playersdf.loc[playersdf['result']==1].groupby('champion')['result'].count()
champwins = champwins.reset_index()

champplays.rename(columns={'result':'number of plays'},inplace=True)
champwins.rename(columns={'result':'number of wins'},inplace=True)

champwinrate = champplays.merge(champwins)
champwinrate['Win Rate'] = champwinrate['number of wins']/champwinrate['number of plays']
champwinrate.loc[champwinrate['Win Rate'] == champwinrate['Win Rate'].max()]

champion  number of plays  number of wins  Win Rate
14  Fiddlesticks                1               1       1.0
25           Jax                1               1       1.0
36       Kog'Maw                1               1       1.0
43      Malphite                1               1       1.0
51      Pantheon                1               1       1.0
71         Urgot                1               1       1.0
73         Vayne                2               2       1.0
78        Yorick                1               1       1.0

Top 5 champions with the most wins

In [0]:
champwins.sort_values(by=['number of wins'],ascending=False).head()

champion  number of wins
29    Kai'Sa              37
76     Xayah              35
20    Gragas              32
38   Lee Sin              30
45  Nautilus              28

Most Flixable Champions

In [0]:
playersdf.groupby('champion')['position'].value_counts()

champion      position
Aatrox        Top          9
              Middle       1
Akali         Middle      24
              Top         11
Alistar       Support     14
Anivia        Middle       1
Ashe          ADC          4
Azir          Middle       4
              Top          1
Bard          Support      1
Blitzcrank    Support      8
Braum         Support      1
Caitlyn       ADC          4
Camille       Top         11
              Middle       3
Cassiopeia    Middle       7
              ADC          1
Cho'gath      Top          5
Corki         Middle       8
Draven        ADC          3
Ekko          Jungle       5
Elise         Jungle      32
Ezreal        ADC         22
              Top          2
              Middle       1
Fiddlesticks  Support      1
Fiora         Top          4
Galio         Middle       8
              Support      7
Gangplank     Top         38
Garen         ADC          8
Gnar          Top         18
Gragas        Jungle      40
              Suppor

Highest number of rules by a champion is 3 rules.

Ezreal (ADC,Middle,Top)

Irelia (ADC,Middle,Top)

Karma (Support,Middle,Top)

Kayle (ADC,Middle,Top)

Lucian (ADC,Middle,Top)

Poppy (Support,Middle,Top)

Pyke (Support,Middle,Top)

Qiyana (Jungle,Middle,Top)

Tristana (ADC,Middle,Top)

Vladimir (ADC,Middle,Top)

Yasuo (ADC,Middle,Top)

Now let's explore the dragons

In [0]:
DragonKilled = teamdf.groupby('team')['teamdragkills'].sum()
DragonKilled = DragonKilled.reset_index()
DragonKilled = DragonKilled.sort_values(by=['teamdragkills'],ascending=False)
DragonKilled.head()

team  teamdragkills
3     Damwon Gaming             57
7   Funplus Phoenix             52
21           Splyce             44
20    SK Telecom T1             44
8        G2 Esports             37

Damwon Gaming has the most dragon kills with 57 dragons followed by Funplus Phoenix	with 52 dragons. 

In [0]:
DragonKilled.tail()

team  teamdragkills
17             Mammoth              9
4   DetonatioN FocusMe              8
9          GAM Esports              7
5             Flamengo              6
0    AHQ e-Sports Club              6

Lowest Number of Dragon kills is 6 by Flamengo and AHQ e-sports Club

In [0]:
DrakeKilled = teamdf.groupby('team')['elementals'].sum()
DrakeKilled = DrakeKilled.reset_index()
DrakeKilled = DrakeKilled.sort_values(by=['elementals'],ascending=False)
DrakeKilled.head()

team  elementals
3     Damwon Gaming          55
7   Funplus Phoenix          50
21           Splyce          43
20    SK Telecom T1          43
8        G2 Esports          36

Splyce has the most Elemental Drake kills with 20 Elemental Drakes followed by Damwon Gaming, Funplus Phoenix and G2 Esports with 18 Elemental Drakes.

In [0]:
gamedragon = teamdf.groupby('gameid')['teamdragkills'].sum()
gamedragon = gamedragon.reset_index()
gamedragon = gamedragon.sort_values(by=['teamdragkills'],ascending=False)
gamedragon.head()

gameid  teamdragkills
51   1070555              8
94   1071627              8
70   1071246              7
109  1072193              7
63   1070986              7

In [0]:
teamdf.loc[(teamdf['gameid']==1070555 )] 

gameid                                                url league  \
178  1070555  http://matchhistory.na.leagueoflegends.com/en/...     WC   
179  1070555  http://matchhistory.na.leagueoflegends.com/en/...     WC   

      split          date   week game  patchno  playerid  side position  \
178  2019-W  43742.335336  PI-RR    3     9.19       100  Blue     Team   
179  2019-W  43742.335336  PI-RR    3     9.19       200   Red     Team   

    player                team champion          ban1    ban2      ban3  \
178   Team       Isurus Gaming           Heimerdinger  Thresh  Nocturne   
179   Team  DetonatioN FocusMe               Pantheon   Yasuo    Lucian   

      ban4     ban5  gamelength  result   k   d   a  teamkills  teamdeaths  \
178  Galio    Karma   63.416667       1  21  16  46         21          16   
179   Ryze  LeBlanc   63.416667       0  16  21  40         16          21   

    doubles triples quadras pentas  fb  fbassist  fbvictim    fbtime  \
178                                  1         0         0  5.350583   
179                                  0         0         1  5.350583   

          kpm      okpm      ckpm  fd     fdtime  teamdragkills  oppdragkills  \
178  0.331143  0.252300  0.583443   0  11.344533              4             4   
179  0.252300  0.331143  0.583443   1  11.344533              4             4   

     elementals  oppelementals  firedrakes  waterdrakes  earthdrakes  \
178           2              3           1            0            0   
179           3              2           0            2            0   

     airdrakes  elders  oppelders  herald  heraldtime  ft     fttime  \
178          1       2          1       1   10.765283   1  11.671083   
179          1       1          2       0   10.765283   0  11.671083   

     firstmidouter  firsttothreetowers  teamtowerkills  opptowerkills  fbaron  \
178              1                   1              11              6     0.0   
179              0                   0               6             11     1.0   

     fbarontime  teambaronkills  oppbaronkills  dmgtochamps  \
178   37.346867               2              2       176971   
179   37.346867               2              2       135843   

     dmgtochampsperminute dmgshare earnedgoldshare  wards       wpm  \
178           2790.607096                             256  4.036794   
179           2142.070959                             270  4.257556   

     wardshare  wardkills      wcpm  visionwards  visionwardbuys  \
178        1.0        112  1.766097           80              82   
179        1.0         92  1.450723           77              88   

    visiblewardclearrate invisiblewardclearrate  totalgold    earnedgpm  \
178              0.62766               0.280303     112687  1143.201051   
179             0.453704               0.230088     104047  1006.959264   

     goldspent      gspd  minionkills  monsterkills  monsterkillsownjungle  \
178     112043  0.036858         1480           409                    270   
179     107988 -0.036858         1357           320                    237   

     monsterkillsenemyjungle       cspm  goldat10  oppgoldat10  gdat10  \
178                       19  29.787122     16166        15208     958   
179                       12  26.444152     15208        16166    -958   

     goldat15  oppgoldat15  gdat15  xpat10  oppxpat10  xpdat10  csat10  \
178     26340        24455    1885   18994      18412      582     347   
179     24455        26340   -1885   18412      18994     -582     293   

     oppcsat10  csdat10  csat15  oppcsat15  csdat15  
178        293       54     545        492       53  
179        347      -54     492        545      -53

In [0]:
teamdf.loc[(teamdf['gameid']==1071627 )]

gameid                                                url league  \
982  1071627  http://matchhistory.na.leagueoflegends.com/en/...     WC   
983  1071627  http://matchhistory.na.leagueoflegends.com/en/...     WC   

      split         date week game  patchno  playerid  side position player  \
982  2019-W  43757.32684    G  7.2     9.19       100  Blue     Team   Team   
983  2019-W  43757.32684    G  7.2     9.19       200   Red     Team   Team   

              team champion          ban1    ban2      ban3      ban4    ban5  \
982  Clutch Gaming           Twisted Fate   Yuumi    Syndra     Rakan  Aatrox   
983         Fnatic                 Qiyana  Rumble  Pantheon  Nautilus  Ezreal   

     gamelength  result   k   d   a  teamkills  teamdeaths doubles triples  \
982       48.65       0  25  25  54         25          25                   
983       48.65       1  25  25  60         25          25                   

    quadras pentas  fb  fbassist  fbvictim    fbtime       kpm      okpm  \
982                  0         0         1  0.695183  0.513875  0.513875   
983                  1         1         0  0.695183  0.513875  0.513875   

         ckpm  fd    fdtime  teamdragkills  oppdragkills  elementals  \
982  1.027749   0  6.944367              4             4           4   
983  1.027749   1  6.944367              4             4           2   

     oppelementals  firedrakes  waterdrakes  earthdrakes  airdrakes  elders  \
982              2           1            0            2          1       0   
983              4           1            0            1          0       2   

     oppelders  herald  heraldtime  ft    fttime  firstmidouter  \
982          2       0     11.8452   1  12.17885              0   
983          0       1     11.8452   0  12.17885              1   

     firsttothreetowers  teamtowerkills  opptowerkills  fbaron  fbarontime  \
982                   0               8             10     0.0     24.9586   
983                   1              10              8     1.0     24.9586   

     teambaronkills  oppbaronkills  dmgtochamps  dmgtochampsperminute  \
982               1              3       140741           2892.929085   
983               3              1       115717           2378.561151   

    dmgshare earnedgoldshare  wards       wpm  wardshare  wardkills      wcpm  \
982                             175  3.597122        1.0         82  1.685509   
983                             179  3.679342        1.0         73  1.500514   

     visionwards  visionwardbuys visiblewardclearrate invisiblewardclearrate  \
982           74              84             0.666667                    0.3   
983           57              61             0.574468               0.234568   

     totalgold    earnedgpm  goldspent      gspd  minionkills  monsterkills  \
982      96444  1342.080164      97658  0.054433         1198           309   
983      96740  1348.164440      92483 -0.054433         1223           270   

     monsterkillsownjungle  monsterkillsenemyjungle       cspm  goldat10  \
982                    188                       40  30.976362     16156   
983                    163                       28  30.688592     17085   

     oppgoldat10  gdat10  goldat15  oppgoldat15  gdat15  xpat10  oppxpat10  \
982        17085    -929     28670        28268     402   19573      19335   
983        16156     929     28268        28670    -402   19335      19573   

     xpdat10  csat10  oppcsat10  csdat10  csat15  oppcsat15  csdat15  
982      238     352        355       -3     535        526        9  
983     -238     355        352        3     526        535       -9

Highest number of dragons killed in a single game is 8 dragons in two games

game between Isurus Gaming and DetonatioN FocusMe

game between Clutch Gaming and Fnatic

In [0]:
teamdf.groupby('team')['teamdragkills'].sum().sum()

530

530 Dragons were killed in the tournment

In [0]:
firedrakesKilled = teamdf.groupby('team')['firedrakes'].sum()
firedrakesKilled = firedrakesKilled.reset_index()
firedrakesKilled = firedrakesKilled.sort_values(by=['firedrakes'],ascending=False)
firedrakesKilled.head()

team  firedrakes
21           Splyce          13
7   Funplus Phoenix          11
10          Griffin          11
3     Damwon Gaming          10
20    SK Telecom T1          10

In [0]:
teamdf.groupby('team')['firedrakes'].sum().sum()

125

125 Inferno Drakes were killed in tournment

Splyce has the most Inferno drake kills with 13 followed by Funplus Phoenix and Griffin with 11

In [0]:
waterdrakesKilled = teamdf.groupby('team')['waterdrakes'].sum()
waterdrakesKilled = waterdrakesKilled.reset_index()
waterdrakesKilled = waterdrakesKilled.sort_values(by=['waterdrakes'],ascending=False)
waterdrakesKilled.head()

team  waterdrakes
3     Damwon Gaming           13
7   Funplus Phoenix           13
2     Clutch Gaming           12
10          Griffin           10
21           Splyce           10

In [0]:
teamdf.groupby('team')['waterdrakes'].sum().sum()

129

129 Ocean Drakes were killed in the tournment

Damown Gaming and Funplus Phoenix have the most water drake kills with 13 followed by Clutch Gaming with 12 

In [0]:
earthdrakesKilled = teamdf.groupby('team')['earthdrakes'].sum()
earthdrakesKilled = earthdrakesKilled.reset_index()
earthdrakesKilled = earthdrakesKilled.sort_values(by=['earthdrakes'],ascending=False)
earthdrakesKilled.head()

team  earthdrakes
3     Damwon Gaming           19
20    SK Telecom T1           14
8        G2 Esports           13
7   Funplus Phoenix           12
21           Splyce           10

In [0]:
teamdf.groupby('team')['earthdrakes'].sum().sum()

133

133 Mountain Drakes were killed in the tournment

Damown Gaming has the most mountain drake kills with 19 followed by SK Telecom T1 with 14 Kills

In [0]:
airdrakesKilled = teamdf.groupby('team')['airdrakes'].sum()
airdrakesKilled = airdrakesKilled.reset_index()
airdrakesKilled = airdrakesKilled.sort_values(by=['airdrakes'],ascending=False)
airdrakesKilled.head()


team  airdrakes
7      Funplus Phoenix         14
3        Damwon Gaming         13
21              Splyce         10
11  Hong Kong Attitude          9
20       SK Telecom T1          9

In [0]:
teamdf.groupby('team')['airdrakes'].sum().sum()

114

144 Cloud Drakes were killed in the tournment

Funplus Phoenix has the most Cloud Drake kills with 14 followed by Damown Gaming with 13 kills

Cloud Drakes were the most killed 144 times followed by mountain drakes with 133 times


In [0]:
eldersKilled = teamdf.groupby('team')['elders'].sum()
eldersKilled = eldersKilled.reset_index()
eldersKilled = eldersKilled.sort_values(by=['elders'],ascending=False)
eldersKilled.head()

team  elders
23  Unicorns of Love       3
6             Fnatic       3
13     Isurus Gaming       3
7    Funplus Phoenix       2
12   Invictus Gaming       2

In [0]:
teamdf.groupby('team')['elders'].sum().sum()

29

Elders was killed 29 times in the tournment

Teams with highed Elder kills are Fnatic, Unicorns of Love and Isurus Gaming with 3 Elder kills

In [0]:
teamdf.groupby('team')['teamdragkills'].sum().nlargest(5)

team
Damwon Gaming      57
Funplus Phoenix    52
SK Telecom T1      44
Splyce             44
G2 Esports         37
Name: teamdragkills, dtype: int64

In [0]:
teamdf.loc[teamdf['gameid']==1070555]

gameid                                                url league  \
178  1070555  http://matchhistory.na.leagueoflegends.com/en/...     WC   
179  1070555  http://matchhistory.na.leagueoflegends.com/en/...     WC   

      split          date   week game  patchno  playerid  side position  \
178  2019-W  43742.335336  PI-RR    3     9.19       100  Blue     Team   
179  2019-W  43742.335336  PI-RR    3     9.19       200   Red     Team   

    player                team champion          ban1    ban2      ban3  \
178   Team       Isurus Gaming           Heimerdinger  Thresh  Nocturne   
179   Team  DetonatioN FocusMe               Pantheon   Yasuo    Lucian   

      ban4     ban5  gamelength  result   k   d   a  teamkills  teamdeaths  \
178  Galio    Karma   63.416667       1  21  16  46         21          16   
179   Ryze  LeBlanc   63.416667       0  16  21  40         16          21   

    doubles triples quadras pentas  fb  fbassist  fbvictim    fbtime  \
178                                  1         0         0  5.350583   
179                                  0         0         1  5.350583   

          kpm      okpm      ckpm  fd     fdtime  teamdragkills  oppdragkills  \
178  0.331143  0.252300  0.583443   0  11.344533              4             4   
179  0.252300  0.331143  0.583443   1  11.344533              4             4   

     elementals  oppelementals  firedrakes  waterdrakes  earthdrakes  \
178           2              3           1            0            0   
179           3              2           0            2            0   

     airdrakes  elders  oppelders  herald  heraldtime  ft     fttime  \
178          1       2          1       1   10.765283   1  11.671083   
179          1       1          2       0   10.765283   0  11.671083   

     firstmidouter  firsttothreetowers  teamtowerkills  opptowerkills  fbaron  \
178              1                   1              11              6     0.0   
179              0                   0               6             11     1.0   

     fbarontime  teambaronkills  oppbaronkills  dmgtochamps  \
178   37.346867               2              2       176971   
179   37.346867               2              2       135843   

     dmgtochampsperminute dmgshare earnedgoldshare  wards       wpm  \
178           2790.607096                             256  4.036794   
179           2142.070959                             270  4.257556   

     wardshare  wardkills      wcpm  visionwards  visionwardbuys  \
178        1.0        112  1.766097           80              82   
179        1.0         92  1.450723           77              88   

    visiblewardclearrate invisiblewardclearrate  totalgold    earnedgpm  \
178              0.62766               0.280303     112687  1143.201051   
179             0.453704               0.230088     104047  1006.959264   

     goldspent      gspd  minionkills  monsterkills  monsterkillsownjungle  \
178     112043  0.036858         1480           409                    270   
179     107988 -0.036858         1357           320                    237   

     monsterkillsenemyjungle       cspm  goldat10  oppgoldat10  gdat10  \
178                       19  29.787122     16166        15208     958   
179                       12  26.444152     15208        16166    -958   

     goldat15  oppgoldat15  gdat15  xpat10  oppxpat10  xpdat10  csat10  \
178     26340        24455    1885   18994      18412      582     347   
179     24455        26340   -1885   18412      18994     -582     293   

     oppcsat10  csdat10  csat15  oppcsat15  csdat15  
178        293       54     545        492       53  
179        347      -54     492        545      -53

In [0]:
maxdragkillsteam = teamdf.groupby(['gameid','team'])['teamdragkills'].sum()
maxdragkillsteam = maxdragkillsteam.reset_index()
maxdragkillsteam.loc[maxdragkillsteam['teamdragkills'] == maxdragkillsteam['teamdragkills'].max()]

gameid           team  teamdragkills
16   1060790  Clutch Gaming              6
152  1071398         J Team              6
218  1072193  Damwon Gaming              6

In [0]:
teamdf.loc[teamdf['gameid']==1060790]

gameid                                                url league  \
394  1060790  https://matchhistory.na.leagueoflegends.com/en...     WC   
395  1060790  https://matchhistory.na.leagueoflegends.com/en...     WC   

      split          date   week game  patchno  playerid  side position  \
394  2019-W  43745.465405  PI-KO    3     9.19       100  Blue     Team   
395  2019-W  43745.465405  PI-KO    3     9.19       200   Red     Team   

    player           team champion      ban1    ban2       ban3    ban4  \
394   Team  Clutch Gaming            Lee Sin  Qiyana       Olaf   Rakan   
395   Team    Royal Youth           Pantheon  Rumble  Gangplank  Irelia   

        ban5  gamelength  result   k   d   a  teamkills  teamdeaths doubles  \
394  Camille   36.983333       1  19   7  36         19           7           
395  LeBlanc   36.983333       0   7  19  21          7          19           

    triples quadras pentas  fb  fbassist  fbvictim  fbtime       kpm  \
394                          1         1         0  4.6977  0.513745   
395                          0         0         1  4.6977  0.189274   

         okpm      ckpm  fd   fdtime  teamdragkills  oppdragkills  elementals  \
394  0.189274  0.703019   1  7.84475              6             0           6   
395  0.513745  0.703019   0  7.84475              0             6           0   

     oppelementals  firedrakes  waterdrakes  earthdrakes  airdrakes  elders  \
394              0           2            3            1          0       0   
395              6           0            0            0          0       0   

     oppelders  herald  heraldtime  ft    fttime  firstmidouter  \
394          0       1    10.74095   1  11.53405              1   
395          0       0    10.74095   0  11.53405              0   

     firsttothreetowers  teamtowerkills  opptowerkills  fbaron  fbarontime  \
394                   1              11              3     1.0     28.4153   
395                   0               3             11     0.0     28.4153   

     teambaronkills  oppbaronkills  dmgtochamps  dmgtochampsperminute  \
394               2              0        65486           1770.689500   
395               0              2        47542           1285.497972   

    dmgshare earnedgoldshare  wards       wpm  wardshare  wardkills      wcpm  \
394                             156  4.218116        1.0         67  1.811627   
395                             132  3.569175        1.0         61  1.649392   

     visionwards  visionwardbuys visiblewardclearrate invisiblewardclearrate  \
394           58              66             0.666667               0.348485   
395           53              57             0.394366               0.395833   

     totalgold   earnedgpm  goldspent      gspd  minionkills  monsterkills  \
394      74983  1378.22082      64275  0.098347          950           292   
395      60005   973.22758      58250 -0.098347         1034           106   

     monsterkillsownjungle  monsterkillsenemyjungle       cspm  goldat10  \
394                    124                       85  33.582695     16759   
395                     85                        4  30.824696     14831   

     oppgoldat10  gdat10  goldat15  oppgoldat15  gdat15  xpat10  oppxpat10  \
394        14831    1928     27891        22434    5457   18795      17181   
395        16759   -1928     22434        27891   -5457   17181      18795   

     xpdat10  csat10  oppcsat10  csdat10  csat15  oppcsat15  csdat15  
394     1614     321        304       17     489        456       33  
395    -1614     304        321      -17     456        489      -33

In [0]:
teamdf.loc[teamdf['gameid']==1071398]

gameid                                                url league  \
754  1071398  http://matchhistory.na.leagueoflegends.com/en/...     WC   
755  1071398  http://matchhistory.na.leagueoflegends.com/en/...     WC   

      split          date week game  patchno  playerid  side position player  \
754  2019-W  43753.442674    G    4     9.19       100  Blue     Team   Team   
755  2019-W  43753.442674    G    4     9.19       200   Red     Team   Team   

       team champion    ban1      ban2      ban3   ban4       ban5  \
754  Splyce            Akali     Kayle  Vladimir  Yasuo      Elise   
755  J Team           Qiyana  Pantheon     Xayah   Olaf  Jarvan IV   

     gamelength  result   k   d   a  teamkills  teamdeaths doubles triples  \
754   44.683333       0   5  16  12          5          16                   
755   44.683333       1  16   5  39         16           5                   

    quadras pentas  fb  fbassist  fbvictim    fbtime       kpm      okpm  \
754                  0         0         1  4.098367  0.111899  0.358075   
755                  1         0         0  4.098367  0.358075  0.111899   

         ckpm  fd    fdtime  teamdragkills  oppdragkills  elementals  \
754  0.469974   0  8.175917              0             6           0   
755  0.469974   1  8.175917              6             0           5   

     oppelementals  firedrakes  waterdrakes  earthdrakes  airdrakes  elders  \
754              5           0            0            0          0       0   
755              0           1            3            1          0       1   

     oppelders  herald  heraldtime  ft    fttime  firstmidouter  \
754          1       1   13.952533   1  14.39645              1   
755          0       0   13.952533   0  14.39645              0   

     firsttothreetowers  teamtowerkills  opptowerkills  fbaron  fbarontime  \
754                   1               4             11     0.0   23.699683   
755                   0              11              4     1.0   23.699683   

     teambaronkills  oppbaronkills  dmgtochamps  dmgtochampsperminute  \
754               0              3        62376           1395.956733   
755               3              0        94894           2123.700112   

    dmgshare earnedgoldshare  wards       wpm  wardshare  wardkills      wcpm  \
754                             143  3.200298        1.0         84  1.879896   
755                             199  4.453562        1.0         59  1.320403   

     visionwards  visionwardbuys visiblewardclearrate invisiblewardclearrate  \
754           47              50             0.609756               0.276596   
755           63              63             0.576923               0.318681   

     totalgold    earnedgpm  goldspent      gspd  minionkills  monsterkills  \
754      74877  1032.886236      70900 -0.148922         1310           230   
755      86269  1287.835882      82308  0.148922         1155           298   

     monsterkillsownjungle  monsterkillsenemyjungle       cspm  goldat10  \
754                    174                        8  34.464752     15368   
755                    189                       28  32.517717     15263   

     oppgoldat10  gdat10  goldat15  oppgoldat15  gdat15  xpat10  oppxpat10  \
754        15263     105     24596        23088    1508   18698      17580   
755        15368    -105     23088        24596   -1508   17580      18698   

     xpdat10  csat10  oppcsat10  csdat10  csat15  oppcsat15  csdat15  
754     1118     350        303       47     546        490       56  
755    -1118     303        350      -47     490        546      -56

In [0]:
teamdf.loc[teamdf['gameid']==1072193]

gameid                                                url league  \
1222  1072193  http://matchhistory.na.leagueoflegends.com/en/...     WC   
1223  1072193  http://matchhistory.na.leagueoflegends.com/en/...     WC   

       split          date week game  patchno  playerid  side position player  \
1222  2019-W  43765.439074   QF    2     9.19       100  Blue     Team   Team   
1223  2019-W  43765.439074   QF    2     9.19       200   Red     Team   Team   

               team champion      ban1    ban2   ban3   ban4      ban5  \
1222     G2 Esports              Akali  Qiyana  Quinn  Kayle  Nautilus   
1223  Damwon Gaming           Pantheon  Syndra  Xayah  Yuumi     Yasuo   

      gamelength  result   k   d   a  teamkills  teamdeaths doubles triples  \
1222   44.366667       0  12  23  24         12          23                   
1223   44.366667       1  23  12  61         23          12                   

     quadras pentas  fb  fbassist  fbvictim    fbtime       kpm      okpm  \
1222                  1         1         0  3.016233  0.270473  0.518407   
1223                  0         0         1  3.016233  0.518407  0.270473   

          ckpm  fd  fdtime  teamdragkills  oppdragkills  elementals  \
1222  0.788881   0  9.5241              1             6           0   
1223  0.788881   1  9.5241              6             1           5   

      oppelementals  firedrakes  waterdrakes  earthdrakes  airdrakes  elders  \
1222              5           0            0            0          0       1   
1223              0           1            0            2          2       1   

      oppelders  herald  heraldtime  ft     fttime  firstmidouter  \
1222          1       0    10.69375   0  14.427183              0   
1223          1       1    10.69375   1  14.427183              1   

      firsttothreetowers  teamtowerkills  opptowerkills  fbaron  fbarontime  \
1222                   0               3             11     0.0     27.3078   
1223                   1              11              3     1.0     27.3078   

      teambaronkills  oppbaronkills  dmgtochamps  dmgtochampsperminute  \
1222               0              3        75115           1693.050338   
1223               3              0        84779           1910.871525   

     dmgshare earnedgoldshare  wards       wpm  wardshare  wardkills  \
1222                             219  4.936138        1.0         66   
1223                             200  4.507889        1.0        100   

          wcpm  visionwards  visionwardbuys visiblewardclearrate  \
1222  1.487603           71              74               0.4625   
1223  2.253944           71              72             0.569767   

     invisiblewardclearrate  totalgold    earnedgpm  goldspent      gspd  \
1222               0.241667      76137  1073.026296      71700 -0.194466   
1223               0.285714      90431  1395.205109      87145  0.194466   

      minionkills  monsterkills  monsterkillsownjungle  \
1222         1199           263                    177   
1223         1202           307                    179   

      monsterkillsenemyjungle       cspm  goldat10  oppgoldat10  gdat10  \
1222                       30  32.952667     15687        15662      25   
1223                       45  34.012021     15662        15687     -25   

      goldat15  oppgoldat15  gdat15  xpat10  oppxpat10  xpdat10  csat10  \
1222     24525        24648    -123   17131      17142      -11     283   
1223     24648        24525     123   17142      17131       11     294   

      oppcsat10  csdat10  csat15  oppcsat15  csdat15  
1222        294      -11     488        478       10  
1223        283       11     478        488      -10

Most Dragon Killed by a team in a single game is 6 by Clutch Gaming gainst Royal Youth and by J team against Splyce and by Damwon Gaming against G2 Esports

In [0]:
teamdf.groupby('team')['herald'].sum().nlargest(5)

team
Damwon Gaming      13
Funplus Phoenix    13
Clutch Gaming      10
SK Telecom T1      10
Splyce             10
Name: herald, dtype: int64

Highest Number of Heralds for a team 13 Heralds for Damwon Gaming and Funplus Phoenix

Lowest Number of Heralds for a team is 1 Heralds for Team Liquid

In [0]:
heraldtime = teamdf.groupby('team')['heraldtime'].mean()
heraldtime = heraldtime.reset_index()
FastestHerald = heraldtime.loc[heraldtime['heraldtime']==heraldtime['heraldtime'].min()]
SlowestHerald = heraldtime.loc[heraldtime['heraldtime']==heraldtime['heraldtime'].max()]
print(FastestHerald)
print(SlowestHerald)

           team  heraldtime
19  Royal Youth   11.198648
                 team  heraldtime
4  DetonatioN FocusMe   15.771146


Fastest Team to get Herald is Royal Youth in 11.19 minutes

Slowest Team to get Herald is Detonation FocusMe in 15.77 minutes

In [0]:
teamdf['heraldtime'].min()

10.395000000000001

In [0]:
teamdf.loc[teamdf['heraldtime'] == teamdf['heraldtime'].min()]

gameid                                                url league  \
706  1061175  https://matchhistory.euw.leagueoflegends.com/e...     WC   
707  1061175  https://matchhistory.euw.leagueoflegends.com/e...     WC   

      split         date week game  patchno  playerid  side position player  \
706  2019-W  43752.50088    G    3     9.19       100  Blue     Team   Team   
707  2019-W  43752.50088    G    3     9.19       200   Red     Team   Team   

                   team champion      ban1    ban2      ban3    ban4     ban5  \
706             Griffin              Quinn   Rakan  Tristana  Thresh  LeBlanc   
707  Hong Kong Attitude           Renekton  Qiyana  Pantheon  Kai'Sa   Lucian   

     gamelength  result   k   d   a  teamkills  teamdeaths doubles triples  \
706       37.85       1  16   9  40         16           9                   
707       37.85       0   9  16  23          9          16                   

    quadras pentas  fb  fbassist  fbvictim  fbtime       kpm      okpm  \
706                  0         0         1  0.7311  0.422721  0.237781   
707                  1         1         0  0.7311  0.237781  0.422721   

         ckpm  fd    fdtime  teamdragkills  oppdragkills  elementals  \
706  0.660502   0  8.282333              3             2           3   
707  0.660502   1  8.282333              2             3           2   

     oppelementals  firedrakes  waterdrakes  earthdrakes  airdrakes  elders  \
706              2           1            1            0          1       0   
707              3           1            1            0          0       0   

     oppelders  herald  heraldtime  ft  fttime  firstmidouter  \
706          0       0      10.395   0  16.315              1   
707          0       1      10.395   1  16.315              0   

     firsttothreetowers  teamtowerkills  opptowerkills  fbaron  fbarontime  \
706                   1               8              2     1.0   35.060417   
707                   0               2              8     0.0   35.060417   

     teambaronkills  oppbaronkills  dmgtochamps  dmgtochampsperminute  \
706               1              0       101396           2678.890357   
707               0              1        39685           1048.480845   

    dmgshare earnedgoldshare  wards       wpm  wardshare  wardkills      wcpm  \
706                             155  4.095112        1.0         87  2.298547   
707                             151  3.989432        1.0         49  1.294584   

     visionwards  visionwardbuys visiblewardclearrate invisiblewardclearrate  \
706           58              59             0.811321               0.424658   
707           46              52             0.430556               0.216867   

     totalgold    earnedgpm  goldspent      gspd  minionkills  monsterkills  \
706      74267  1313.733157      66076  0.120607         1178           255   
707      62624  1006.124174      58560 -0.120607         1068           206   

     monsterkillsownjungle  monsterkillsenemyjungle       cspm  goldat10  \
706                    165                       22  37.859974     16552   
707                    144                        4  33.659181     16571   

     oppgoldat10  gdat10  goldat15  oppgoldat15  gdat15  xpat10  oppxpat10  \
706        16571     -19     24605        24404     201   19230      18652   
707        16552      19     24404        24605    -201   18652      19230   

     xpdat10  csat10  oppcsat10  csdat10  csat15  oppcsat15  csdat15  
706      578     351        331       20     539        511       28  
707     -578     331        351      -20     511        539      -28

The fastest Herald killd was after 10.39 minutes by Hong Kong Attitude against Griffin

In [0]:
teamdf.groupby('team')['ft'].sum().nlargest(5)

team
Funplus Phoenix    13
SK Telecom T1      12
Damwon Gaming      11
Splyce              9
Clutch Gaming       8
Name: ft, dtype: int64

Most First Tower by a team is 13 times by Funplus Phoenix followed by 12 times by SK Telecom T1


In [0]:
ftwr = teamdf.groupby(['team','ft'])['result'].sum()
ftwr = ftwr.reset_index()
ftwr.head()

team  ft  result
0  AHQ e-Sports Club   0       0
1  AHQ e-Sports Club   1       0
2             Cloud9   0       0
3             Cloud9   1       2
4      Clutch Gaming   0       0

In [0]:
ftwr.groupby('ft')['result'].sum()

ft
0    36
1    83
Name: result, dtype: int64

In [0]:
83/(36+83)

0.6974789915966386

The team who kill the first tower wins 70% of the time

In [0]:
maxftt = teamdf['fttime'].max()
maxfttgameid = teamdf.loc[teamdf['fttime']==teamdf['fttime'].max()]['gameid'].tolist()[0]
maxfttteams = teamdf.loc[teamdf['gameid']==maxfttgameid]['team'].tolist()
maxfttteam = teamdf.loc[teamdf['fttime']==teamdf['fttime'].max()]['team'].tolist()[1]
print('Longest Time to kill the first tower was {} minutes in the game between {} and {} and was killed by {}.'.format("%.2f" %maxftt,maxfttteams[0],maxfttteams[1],maxfttteam))

Longest Time to kill the first tower was 20.81 minutes in the game between Royal Never Give Up and SK Telecom T1 and was killed by SK Telecom T1.


In [0]:
minftt = teamdf['fttime'].min()
minfttgameid = teamdf.loc[teamdf['fttime']==teamdf['fttime'].min()]['gameid'].tolist()[0]
minfttteams = teamdf.loc[teamdf['gameid']==minfttgameid]['team'].tolist()
minfttteam = teamdf.loc[teamdf['fttime']==teamdf['fttime'].min()]['team'].tolist()[0]
print('Shortest Time to kill the first tower was {} minutes in the game between {} and {} and was killed by {}.'.format("%.2f" %minftt,minfttteams[0],minfttteams[1],minfttteam))

Shortest Time to kill the first tower was 7.76 minutes in the game between Funplus Phoenix and G2 Esports and was killed by Funplus Phoenix.


In [0]:
print("Average time taken to kill the first tower is","%.2f" %teamdf['fttime'].mean(),"minutes.")

Average time taken to kill the first tower is 13.76 minutes.


Let's explore the mid tower same as we did with the first tower


In [0]:
teamdf.groupby('team')['firstmidouter'].sum().nlargest(5)

team
Damwon Gaming      13
Splyce             13
Funplus Phoenix    11
G2 Esports         10
SK Telecom T1       8
Name: firstmidouter, dtype: int64

Most Mid Tower first Kill by a team is 13 times by Splyce and Damwon Gaming followed by 11 times by Funplus Phoenix

In [0]:
ftwr = teamdf.groupby(['team','firstmidouter'])['result'].sum()
ftwr = ftwr.reset_index()
ftwr.groupby('firstmidouter')['result'].sum()

firstmidouter
0    29
1    90
Name: result, dtype: int64

In [0]:
90/119

0.7563025210084033

The team who kill the Mid tower first wins 76% of the time

Now let's do the same with the first three towers

In [0]:
teamdf.groupby('team')['firsttothreetowers'].sum().nlargest(5)

team
Damwon Gaming      12
Funplus Phoenix    12
Splyce             12
G2 Esports         11
SK Telecom T1       9
Name: firsttothreetowers, dtype: int64

Most first three towers killed by a team is 12 times by Damwongaming, Funplus Phoenix and Splyce followed by G2 Esports with 11 times

In [0]:
ftwr = teamdf.groupby(['team','firsttothreetowers'])['result'].sum()
ftwr = ftwr.reset_index()
ftwr.groupby('firsttothreetowers')['result'].sum()

firsttothreetowers
0    23
1    96
Name: result, dtype: int64

In [0]:
96/119

0.8067226890756303

The team who kill 3 towers first wins 81% of the time

In [0]:
teamdf.groupby('team')['teamtowerkills'].sum().nlargest(5)

team
Damwon Gaming      143
Funplus Phoenix    140
Splyce             133
G2 Esports         124
SK Telecom T1      106
Name: teamtowerkills, dtype: int64

Most Killed Towers by a team is 143 towers by Damwon Gaming followed by Funplus Phoenix with 140 towers

Least Killed Towers by a team is 13 towers by AHQ e-Sports Club

Now Let's Explore Barons

In [0]:
teamdf.groupby('team')['fbaron'].sum().nlargest(5)

team
Damwon Gaming      13.0
Funplus Phoenix    13.0
Splyce             12.0
SK Telecom T1      10.0
G2 Esports          8.0
Name: fbaron, dtype: float64

Most first baron kills by a team is 13 times by Damwon Gaming and Funplus Phoenix followed by Splyce with 12 times.

In [0]:
ftwr = teamdf.groupby(['team','fbaron'])['result'].sum()
ftwr = ftwr.reset_index()
ftwr.groupby('fbaron')['result'].sum()

fbaron
0.0     14
1.0    101
Name: result, dtype: int64

Baron wasn't killed in only 4 games of the tournment

In [0]:
101/119

0.8487394957983193

The team who kill the first baron wins 85% of the time

In [0]:
maxfb = teamdf['fbarontime'].max()
maxfbgameid = teamdf.loc[teamdf['fbarontime']==teamdf['fbarontime'].max()]['gameid'].tolist()[0]
maxfbteams = teamdf.loc[teamdf['gameid']==maxfbgameid]['team'].tolist()
maxfbteam = teamdf.loc[teamdf['fbarontime']==teamdf['fbarontime'].max()]['team'].tolist()[0]
print('Longest Time to kill the first Baron was {} minutes in the game between {} and {} and was killed by {}.'.format("%.2f" %maxfb,maxfbteams[0],maxfbteams[1],maxfbteam))

Longest Time to kill the first Baron was 37.36 minutes in the game between Cloud9 and Hong Kong Attitude and was killed by Cloud9.


In [0]:
minfb = teamdf['fbarontime'].min()
minfbgameid = teamdf.loc[teamdf['fbarontime']==teamdf['fbarontime'].min()]['gameid'].tolist()[0]
minfbteams = teamdf.loc[teamdf['gameid']==minfbgameid]['team'].tolist()
minfbteam = teamdf.loc[teamdf['fbarontime']==teamdf['fbarontime'].min()]['team'].tolist()[1]
print('Shortest Time to kill the first baron was {} minutes in the game between {} and {} and was killed by {}.'.format("%.2f" %minfb,minfbteams[0],minfbteams[1],minfbteam))

Shortest Time to kill the first baron was 20.26 minutes in the game between G2 Esports and Funplus Phoenix and was killed by Funplus Phoenix.


In [0]:
teamdf.groupby('team')['teambaronkills'].sum().nlargest(5)

team
Splyce             19
Funplus Phoenix    18
Damwon Gaming      17
SK Telecom T1      16
G2 Esports         10
Name: teambaronkills, dtype: int64

The Team who killed baron the most is Splyce 19 times followed by Funplus Phoenix with 18 times

Now Let's Explore The Damage dealt to champions

First for teams

In [0]:
teamdf.groupby('team')['dmgtochamps'].sum().nlargest(5)

team
Splyce             1226722
Funplus Phoenix    1098078
Damwon Gaming      1013863
G2 Esports          983356
Invictus Gaming     946809
Name: dmgtochamps, dtype: int64

Most Damage dealt by a team over the tournment length is 1226722 by Splyce followed by 1098078 by Funplus Phoenix

In [0]:
teamdf.groupby('team')['dmgtochamps'].mean().nlargest(5)

team
DetonatioN FocusMe    79021.750000
Isurus Gaming         72031.750000
Cloud9                68793.333333
Unicorns of Love      68438.900000
Griffin               67939.909091
Name: dmgtochamps, dtype: float64

Highest Average Damage dealt by a team is 79021.75 by team DetonatioN FocusMe followed by Isurus Gaming with 72031.75

In [0]:
teamdf.groupby('team')['dmgtochamps'].max().nlargest(5)

team
Isurus Gaming         176971
Cloud9                144556
Clutch Gaming         140741
Griffin               136108
DetonatioN FocusMe    135843
Name: dmgtochamps, dtype: int64

In [0]:
DamageteamGameID = teamdf.loc[teamdf['dmgtochamps']==teamdf['dmgtochamps'].max()]['gameid'].tolist()[0]
teamdf.loc[teamdf['gameid']==DamageteamGameID]

gameid                                                url league  \
178  1070555  http://matchhistory.na.leagueoflegends.com/en/...     WC   
179  1070555  http://matchhistory.na.leagueoflegends.com/en/...     WC   

      split          date   week game  patchno  playerid  side position  \
178  2019-W  43742.335336  PI-RR    3     9.19       100  Blue     Team   
179  2019-W  43742.335336  PI-RR    3     9.19       200   Red     Team   

    player                team champion          ban1    ban2      ban3  \
178   Team       Isurus Gaming           Heimerdinger  Thresh  Nocturne   
179   Team  DetonatioN FocusMe               Pantheon   Yasuo    Lucian   

      ban4     ban5  gamelength  result   k   d   a  teamkills  teamdeaths  \
178  Galio    Karma   63.416667       1  21  16  46         21          16   
179   Ryze  LeBlanc   63.416667       0  16  21  40         16          21   

    doubles triples quadras pentas  fb  fbassist  fbvictim    fbtime  \
178                                  1         0         0  5.350583   
179                                  0         0         1  5.350583   

          kpm      okpm      ckpm  fd     fdtime  teamdragkills  oppdragkills  \
178  0.331143  0.252300  0.583443   0  11.344533              4             4   
179  0.252300  0.331143  0.583443   1  11.344533              4             4   

     elementals  oppelementals  firedrakes  waterdrakes  earthdrakes  \
178           2              3           1            0            0   
179           3              2           0            2            0   

     airdrakes  elders  oppelders  herald  heraldtime  ft     fttime  \
178          1       2          1       1   10.765283   1  11.671083   
179          1       1          2       0   10.765283   0  11.671083   

     firstmidouter  firsttothreetowers  teamtowerkills  opptowerkills  fbaron  \
178              1                   1              11              6     0.0   
179              0                   0               6             11     1.0   

     fbarontime  teambaronkills  oppbaronkills  dmgtochamps  \
178   37.346867               2              2       176971   
179   37.346867               2              2       135843   

     dmgtochampsperminute dmgshare earnedgoldshare  wards       wpm  \
178           2790.607096                             256  4.036794   
179           2142.070959                             270  4.257556   

     wardshare  wardkills      wcpm  visionwards  visionwardbuys  \
178        1.0        112  1.766097           80              82   
179        1.0         92  1.450723           77              88   

    visiblewardclearrate invisiblewardclearrate  totalgold    earnedgpm  \
178              0.62766               0.280303     112687  1143.201051   
179             0.453704               0.230088     104047  1006.959264   

     goldspent      gspd  minionkills  monsterkills  monsterkillsownjungle  \
178     112043  0.036858         1480           409                    270   
179     107988 -0.036858         1357           320                    237   

     monsterkillsenemyjungle       cspm  goldat10  oppgoldat10  gdat10  \
178                       19  29.787122     16166        15208     958   
179                       12  26.444152     15208        16166    -958   

     goldat15  oppgoldat15  gdat15  xpat10  oppxpat10  xpdat10  csat10  \
178     26340        24455    1885   18994      18412      582     347   
179     24455        26340   -1885   18412      18994     -582     293   

     oppcsat10  csdat10  csat15  oppcsat15  csdat15  
178        293       54     545        492       53  
179        347      -54     492        545      -53

The Highest Damage Dealt by a team in a single game is 176971 by Isurus Gaming against DetonatioN FocusMe

In [0]:
teamdf.groupby('gameid')['dmgtochamps'].sum().max()

312814

The Highest Damage Dealth in a single game from both teams is 312814 in the game between Isurus Gaming and DetonatioN FocusMe

Now let's explore the damage for players

In [0]:
playersdf.groupby('player')['dmgtochamps'].sum().nlargest(5)

player
Humanoid      336503
Kobbe         308664
Vizicsacsi    292705
Nuguri        289340
Doinb         282318
Name: dmgtochamps, dtype: int64

The Highest Damage dealt by a player in the tournment is 336503 by Humanoid followed by 308664 by Kobbe

The Highest Damage dealt by a player in the tournment without playing in the play-in stage is 282318 by Doinb 

In [0]:
playersdf.groupby('player')['dmgtochamps'].mean().nlargest(5)

player
Sneaky     25142.600
Ceros      23296.750
Buggax     22502.125
Nomanz     21086.900
Yutapon    20849.000
Name: dmgtochamps, dtype: float64

The Highest Average Damage dealt per game by a player is 25142.6 by Sneaky followed by Ceros with 23296.75

In [0]:
playersdf.groupby(['player'])['dmgtochamps'].max().nlargest(5)

player
Sneaky        66398
Ceros         56278
Huni          56189
Kaiwing       53214
JackeyLove    51971
Name: dmgtochamps, dtype: int64

In [0]:
DamagePlayerGameID = playersdf.loc[playersdf['dmgtochamps']==playersdf['dmgtochamps'].max()]['gameid'].tolist()[0]
playersdf.loc[playersdf['gameid']==DamagePlayerGameID]

gameid                                                url league  \
636  1071297  http://matchhistory.na.leagueoflegends.com/en/...     WC   
637  1071297  http://matchhistory.na.leagueoflegends.com/en/...     WC   
638  1071297  http://matchhistory.na.leagueoflegends.com/en/...     WC   
639  1071297  http://matchhistory.na.leagueoflegends.com/en/...     WC   
640  1071297  http://matchhistory.na.leagueoflegends.com/en/...     WC   
641  1071297  http://matchhistory.na.leagueoflegends.com/en/...     WC   
642  1071297  http://matchhistory.na.leagueoflegends.com/en/...     WC   
643  1071297  http://matchhistory.na.leagueoflegends.com/en/...     WC   
644  1071297  http://matchhistory.na.leagueoflegends.com/en/...     WC   
645  1071297  http://matchhistory.na.leagueoflegends.com/en/...     WC   

      split          date week game  patchno  playerid  side position  \
636  2019-W  43751.490046    G    2     9.19         1  Blue      Top   
637  2019-W  43751.490046    G    2     9.19         2  Blue   Jungle   
638  2019-W  43751.490046    G    2     9.19         3  Blue   Middle   
639  2019-W  43751.490046    G    2     9.19         4  Blue      ADC   
640  2019-W  43751.490046    G    2     9.19         5  Blue  Support   
641  2019-W  43751.490046    G    2     9.19         6   Red      Top   
642  2019-W  43751.490046    G    2     9.19         7   Red   Jungle   
643  2019-W  43751.490046    G    2     9.19         8   Red   Middle   
644  2019-W  43751.490046    G    2     9.19         9   Red      ADC   
645  2019-W  43751.490046    G    2     9.19        10   Red  Support   

         player                team      champion      ban1          ban2  \
636    Licorice              Cloud9      Renekton     Quinn  Twisted Fate   
637  Svenskeren              Cloud9         Elise     Quinn  Twisted Fate   
638       Nisqy              Cloud9        Irelia     Quinn  Twisted Fate   
639      Sneaky              Cloud9  Heimerdinger     Quinn  Twisted Fate   
640      Zeyzal              Cloud9      Nautilus     Quinn  Twisted Fate   
641          3z  Hong Kong Attitude         Akali  Pantheon        Syndra   
642       Crash  Hong Kong Attitude        Gragas  Pantheon        Syndra   
643     M1ssion  Hong Kong Attitude      Tristana  Pantheon        Syndra   
644     Unified  Hong Kong Attitude         Garen  Pantheon        Syndra   
645     Kaiwing  Hong Kong Attitude         Yuumi  Pantheon        Syndra   

        ban3    ban4    ban5  gamelength  result  k  d   a  teamkills  \
636  Rek'Sai  Veigar  Kai'Sa   47.033333       1  6  1   3         18   
637  Rek'Sai  Veigar  Kai'Sa   47.033333       1  4  5   9         18   
638  Rek'Sai  Veigar  Kai'Sa   47.033333       1  3  6   7         18   
639  Rek'Sai  Veigar  Kai'Sa   47.033333       1  3  3  12         18   
640  Rek'Sai  Veigar  Kai'Sa   47.033333       1  2  4  10         18   
641    Xayah  Qiyana    Pyke   47.033333       0  5  4   4         19   
642    Xayah  Qiyana    Pyke   47.033333       0  1  6  12         19   
643    Xayah  Qiyana    Pyke   47.033333       0  5  2   2         19   
644    Xayah  Qiyana    Pyke   47.033333       0  5  4   8         19   
645    Xayah  Qiyana    Pyke   47.033333       0  3  2  11         19   

     teamdeaths doubles triples quadras pentas  fb  fbassist  fbvictim  \
636          19       2       1       0      0   0         0         0   
637          19       0       0       0      0   0         0         0   
638          19       0       0       0      0   1         0         0   
639          19       0       0       0      0   0         0         0   
640          19       0       0       0      0   0         0         0   
641          18       1       0       0      0   0         0         0   
642          18       0       0       0      0   0         0         0   
643          18       0       0       0      0   0         0         1   
644          18       1       0       0      0   0         0         

Most Damage dealt by a player in a single game was 66398 by Sneaky on Heimerdinger in the game between Cloud9 and Hong Kong Attitude

In [0]:
teamdf.groupby('team')['dmgtochampsperminute'].mean().nlargest(5)

team
Invictus Gaming       2015.910340
Griffin               2005.952127
Funplus Phoenix       1933.971633
Fnatic                1869.681700
DetonatioN FocusMe    1869.016640
Name: dmgtochampsperminute, dtype: float64

Highest Average Damage per Minute Teams is Invictus Gaming with 2015.19 damage per minute dealt followed by Griffin with 2005.95

In [0]:
playersdf.groupby('player')['dmgtochampsperminute'].mean().nlargest(5)

player
Sneaky    614.774582
TheShy    590.676725
Nomanz    562.201874
Huni      556.685442
Uzi       555.537543
Name: dmgtochampsperminute, dtype: float64

Highest average damage dealt per minute by a player is 614.77 by Sneaky followed by TheShy with 590.67 damage dealt per minute

In [0]:
playersdf.groupby('player')['dmgshare'].mean().nlargest(5)

DataError: ignored

In [0]:
playersdf.groupby('player')['earnedgoldshare'].mean().nlargest(5)

DataError: ignored

apparently dmgshare and earnedgoldshare columns are object type and have some bad values and can't be transformed to numerical values, let's try to solve this

In [0]:
ds = []
for i in playersdf['dmgshare'].tolist():
    try:
      ds.append(float(i))
    except:
      ds.append(float(0)) 


In [0]:
playersdf['damageshare'] = ds

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [0]:
playersdf[['player','dmgshare','damageshare']].head()

player  dmgshare  damageshare
0      Evi  0.312067     0.312067
1    Steal  0.213422     0.213422
2    Ceros  0.203512     0.203512
3  Yutapon  0.198449     0.198449
4    Gaeng   0.07255     0.072550

In [0]:
gs = []
for i in playersdf['earnedgoldshare'].tolist():
    try:
      gs.append(float(i))
    except:
      gs.append(float(0)) 


In [0]:
playersdf['goldshare'] = gs

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [0]:
playersdf[['player','earnedgoldshare','goldshare']].head()

player earnedgoldshare  goldshare
0      Evi        0.206844   0.206844
1    Steal        0.166862   0.166862
2    Ceros        0.210106   0.210106
3  Yutapon        0.300743   0.300743
4    Gaeng        0.115445   0.115445

Ok now everything is good, let's continue

In [0]:
playersdf.groupby('player')['damageshare'].mean().nlargest(5)

player
Uzi       0.372404
Buggax    0.320726
Huni      0.319019
Nomanz    0.310548
DeuL      0.308937
Name: damageshare, dtype: float64

The Highest average damage share of the team for a player is 37.2% for Uzi from Royals Never Give Up followed by 32% for Buggax from Isurus Gaming.

In [0]:
playersdf.groupby('player')['goldshare'].mean().nlargest(5)

player
k1ng          0.308346
Uzi           0.303716
Doublelift    0.290202
Yutapon       0.286884
DeuL          0.285540
Name: goldshare, dtype: float64

The Highest average gold share of the team for a player is 30.8% for K1ng from MAMMOTH followed by 30.3% for Uzi from Royals Never Give Up.

Now Let's explore Wards 

In [0]:
teamdf.groupby('team')['wards'].sum().nlargest(5)

team
Splyce             2494
G2 Esports         2372
Damwon Gaming      2268
Funplus Phoenix    2253
SK Telecom T1      2041
Name: wards, dtype: int64

The Highest amount of wards through the tournment by a team is 2494 wards by Splyce followed by 2372 by G2 Esports

In [0]:
teamdf.groupby('team')['wards'].mean().nlargest(5)

team
DetonatioN FocusMe     161.500000
Royal Never Give Up    151.000000
SK Telecom T1          145.785714
Isurus Gaming          141.125000
Griffin                139.000000
Name: wards, dtype: float64

The Highest average amount of wards per game by a team is 161.5 wards by DetonatioN FocusMe followed by 151 by Royal Never Give Up

In [0]:
playersdf.groupby('player')['wards'].sum().nlargest(5)

player
Norskeren    1038
Mikyx        1010
BeryL        1007
Crisp         954
Baolan        812
Name: wards, dtype: int64

The Highest Amount of wards for the tournment is 1038 by Norskeren followed by 1010 by Mikyx

In [0]:
playersdf.groupby('player')['wards'].mean().nlargest(5)

player
Slow     69.250000
Ming     66.500000
Gaeng    62.500000
Koala    61.833333
Mata     60.500000
Name: wards, dtype: float64

The Highest average amount of wards per game by a player is 69.25 wards by Slow followed by 66.5 by Ming

In [0]:
teamdf.groupby('team')['wpm'].mean().nlargest(5)

team
SK Telecom T1          4.408983
Royal Never Give Up    4.350924
Griffin                4.209627
G2 Esports             4.033412
J Team                 4.031726
Name: wpm, dtype: float64

The Highest Average Wards Per Minutes is 4.4 WPM by Sk Telecom T1 followed by 4.35 by Royal Never Give Up

In [0]:
playersdf.groupby('player')['wpm'].mean().nlargest(5)

player
Ming      1.908831
Koala     1.840720
Effort    1.813702
Mata      1.789732
Slow      1.726409
Name: wpm, dtype: float64

The Highest Average Wards Per Minutes is 1.9 by Ming followed by 1.84 by Koala

In [0]:
playersdf.groupby('player')['wardshare'].mean().nlargest(5)

player
Destiny    0.491527
Baolan     0.484793
Slow       0.480803
Koala      0.460085
CoreJJ     0.458045
Name: wardshare, dtype: float64

Highest Share of team’s total wards placed (of all types) is 49.15% by Destingy followed by 48.47% by Baolan

In [0]:
teamdf.groupby('team')['wardkills'].sum().nlargest(5)

team
Splyce             1116
G2 Esports         1041
Damwon Gaming       981
Funplus Phoenix     898
SK Telecom T1       810
Name: wardkills, dtype: int64

Highest number of wards killed by a team is 1116 by Splyce followed by 1041 by G2 Esports

In [0]:
playersdf.groupby('player')['wardkills'].sum().nlargest(5)

player
Jankos       329
Norskeren    302
Xerxe        299
Tian         282
Mikyx        272
Name: wardkills, dtype: int64

Highest number of wards killed by a player is 329 by Jankos followed by 302 by Norskeren

In [0]:
teamdf.groupby('team')['wcpm'].mean().nlargest(5)

team
Royal Never Give Up    2.028967
Griffin                1.778831
G2 Esports             1.769023
SK Telecom T1          1.738290
Clutch Gaming          1.694029
Name: wcpm, dtype: float64

Highest average number of cleared wards per minutes is 2 by Royal Never Give Up followed by 1.77 for Griffin

In [0]:
teamdf.groupby('team')['visionwards'].sum().nlargest(5)

team
Splyce             862
Damwon Gaming      815
G2 Esports         785
SK Telecom T1      738
Funplus Phoenix    736
Name: visionwards, dtype: int64

Highest number of vision/control wards by a team is 862 by Splyce followed by 815 by Damwon Gaming

In [0]:
playersdf.groupby('player')['visionwards'].sum().nlargest(5)

player
Mikyx        345
BeryL        327
Norskeren    303
Crisp        299
Baolan       277
Name: visionwards, dtype: int64

Highest number of vision/control wards by a player is 345 by Mikyx followed by 327 by BeryL

In [0]:
teamdf.groupby('team')['totalgold'].sum().nlargest(5)

team
Splyce             1257971
Damwon Gaming      1114693
Funplus Phoenix    1088766
G2 Esports         1064673
SK Telecom T1       883913
Name: totalgold, dtype: int64

Max Amount of gold earned by a team is 1257971 by Splyce followed by 1114693 by Damwon Gaming

Max Amount of gold earned by a team that didn't play in the play-in stage is 1088766 by Funplus Phoenix followed by 1064673 by G2 Esports

In [0]:
playersdf.groupby('player')['totalgold'].sum().nlargest(5)

player
Kobbe         318058
Humanoid      285079
Lwx           271084
Perkz         269484
Vizicsacsi    264397
Name: totalgold, dtype: int64

Max Amount of gold earned by a player is 318058 by Kobbe followed by 285079 by Humanoid

Max Amount of gold earned by a player that didn't play in the play-in stage is 271084 by Lwx followed by 269484 by Perkz

In [0]:
teamdf.groupby('team')['totalgold'].mean().nlargest(5)

team
DetonatioN FocusMe     68171.750000
Isurus Gaming          67807.500000
Royal Never Give Up    64686.333333
MEGA Esports           63661.500000
Unicorns of Love       63490.000000
Name: totalgold, dtype: float64

Max Average Gold earned by a team per game is 68171.75 by DetonatioN FocusMe followed by 67807.5 by Isurus Gaming

In [0]:
playersdf.groupby('player')['totalgold'].mean().nlargest(5)

player
Yutapon       17411.000000
Warangelus    17312.500000
Uzi           17301.166667
DeuL          16082.000000
Kobbe         15902.900000
Name: totalgold, dtype: float64

Max Average Gold earned by a player per game is 17411 by Yutapon followed by 17312.5 by Warangelus

In [0]:
teamdf.groupby('team')['earnedgpm'].mean().nlargest(5)

team
Funplus Phoenix        1290.161046
Damwon Gaming          1274.212163
SK Telecom T1          1264.040831
Griffin                1217.809569
Royal Never Give Up    1212.483851
Name: earnedgpm, dtype: float64

Highest average Gold Per Minute by a team is 1290.16 by Funplus Phoenix followed by 1274.21 by Damwon Gaming

In [0]:
playersdf.groupby('player')['earnedgpm'].mean().nlargest(5)

player
Uzi      366.461492
Lwx      351.227676
Teddy    337.203039
Kobbe    335.963124
Perkz    332.910822
Name: earnedgpm, dtype: float64

Highest average Gold Per Minute by a player is 366.46 by Uzi followed by 351.22 by Lwx

In [0]:
teamdf.groupby('team')['minionkills'].sum().nlargest(5)

team
Splyce                18106
Damwon Gaming         15660
G2 Esports            15456
Funplus Phoenix       14258
Hong Kong Attitude    12612
Name: minionkills, dtype: int64

Max amount of minion killed by a team is 18106 by Splyce followed by Damwon Gaming by 15660

Max amount of minion killed by a team that didn't play in the play-in stage is 15456 by G2 Esports followed by Funplus Phoenix with 14258

In [0]:
playersdf.groupby('player')['minionkills'].sum().nlargest(5)

player
Kobbe         6147
Humanoid      5591
Perkz         5200
Vizicsacsi    5010
Lwx           4925
Name: minionkills, dtype: int64

Max amount of minion killed by a player is 6147 by kobbe followed by Humanoid by 5591

Max amount of minion killed by a player who didn't play in the play-in stage is 5200 by Perkz followed by Lwx with 4925

In [0]:
playersdf.groupby('player')['monsterkills'].sum().nlargest(5)

player
Canyon    2401
Xerxe     2362
Tian      2309
Jankos    2209
Crash     1975
Name: monsterkills, dtype: int64

Max amount of Monsters killed by a jungler is 2401 by Canyon followed by Xerxe with 2362

Max amount of Monsters killed by a jungler that didn't play in the play-in stage is 2309 by Tian followed by Jankos with 2209

In [0]:
teamdf.groupby('team')['cspm'].mean().nlargest(5)

team
GAM Esports            33.962788
Damwon Gaming          33.774703
SK Telecom T1          33.423809
Royal Never Give Up    33.340447
G2 Esports             32.955312
Name: cspm, dtype: float64

Highest average Creep Score per minute for a team is 33.96 by GAM Esports followed by Damwon Gaming with 33.77

In [0]:
playersdf.groupby('player')['cspm'].mean().nlargest(5)

player
Uzi           11.120991
MnM           10.978102
k1ng          10.544127
DeuL          10.200089
Doublelift     9.998924
Name: cspm, dtype: float64

Highest average Creep Score per minute for a player is 11.12 by Uzi followed by MnM with 10.97

In [0]:
teamdf.groupby('team')['csdat10'].mean().nlargest(5)

team
Invictus Gaming    19.928571
Clutch Gaming      14.615385
G2 Esports         14.333333
MEGA Esports       12.750000
GAM Esports        10.666667
Name: csdat10, dtype: float64

Highest average CS difference at 10 by a team is 19.92 by Invictus Gaming followed by Clutch Gaming with 14.61

In [0]:
playersdf.groupby('player')['csdat10'].mean().nlargest(5)

player
Rockky    15.500000
Zeyzal    13.666667
Uzi       12.666667
Zeros     11.166667
k1ng      10.600000
Name: csdat10, dtype: float64

Highest average CS difference at 10 by a player is 15.5 by Rockky followed by Zeyzal with 13.66

In [0]:
teamdf.groupby('team')['gdat15'].mean().nlargest(5)

team
Funplus Phoenix    1762.666667
Griffin            1189.090909
Damwon Gaming      1035.500000
Clutch Gaming      1018.538462
SK Telecom T1       948.428571
Name: gdat15, dtype: float64

Highest average Gold Difference at 15 minutes by a team is 1762.66 by Funplus Phoenix followed by Griffin with 1189.09

In [0]:
playersdf.groupby(['player'])['gdat15'].mean().nlargest(5)

player
Blaber    909.333333
TheShy    705.285714
Kobbe     670.350000
Rockky    652.250000
Khan      597.000000
Name: gdat15, dtype: float64

Highest average Gold difference at 15 minutes by a player is 909.33 by Blabler

In [0]:
teamdf.groupby('team')['xpdat10'].mean().nlargest(5)

team
SK Telecom T1      388.357143
Griffin            378.363636
Funplus Phoenix    306.055556
MEGA Esports       232.000000
G2 Esports         213.111111
Name: xpdat10, dtype: float64

Highest average XP difference for a team is 388.35 by SK Telecom T1 followed by Griffin with 378.36

In [0]:
playersdf.groupby('player')['xpdat10'].mean().nlargest(5)

player
Shrimp    454.600000
Rockky    303.250000
Armut     271.750000
Lwx       264.277778
Lira      250.461538
Name: xpdat10, dtype: float64

Highest average XP difference for a player is 454.6 by Shrimp followed by Rockky with 303.25